$ErrorActionPreference = 'Stop'
$Script = Join-Path (Split-Path -Parent $PSScriptRoot) 'Invoke-PhaseMerge.ps1'
$Text = Get-Content -LiteralPath $Script -Raw -Encoding UTF8
& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $Script -SelfTest
if ($LASTEXITCODE -ne 0) { throw 'positive self-test failed' }
& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $Script -Mode 'Unknown'
if ($LASTEXITCODE -eq 0) { throw 'negative unknown mode was accepted' }
$Root = (Resolve-Path (Join-Path $PSScriptRoot '..\..\..\..')).Path
& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $Script -TaskId 'TASK-P10-999' -ControlRepo $Root -SourceWorktree $Root -LandingEvidenceRoot (Join-Path $Root 'docs/execution/evidence') -Mode 'Cleanup'
if ($LASTEXITCODE -eq 0) { throw 'negative missing cross-shell state was accepted' }
foreach($Marker in @('TASK-P10-999','p10_999_formal_preflight_failed','approval_only_diff_invalid','governance_receipt_valid','minimum_nonoverlap_observation_hours=744','nonoverlap_failure_count','minimum_total_observation_failure_count','rollout_artifact_hash_mismatch','git merge --no-ff --no-edit','Push-Location -LiteralPath $LandingRoot','parent_count','approval_tip_tree','Invoke-IntegrationSmoke.ps1','smoke_attestation_oid','within_48_hours','manifest_self_reference_count','phase_close_chain_valid','valid_secret_finding_count','identity_denied_mismatch','authorization_bypass_count','git revert -m 1')){if(-not$Text.Contains($Marker)){throw "negative: PhaseMerge missing required P10-999 marker $Marker"}}
foreach($Marker in @('TASK-P11-999','p11_999_formal_preflight_failed','codex/phase-11-rag','P11-990/approval-receipts.json','P11-999/merge-authorization.json','current_source_tip_after_approval_only_evidence','Data','Privacy','parallel_phase12_ref_count','acceptance_gate_invalid','merge_authorization_hash_mismatch','production_same_configuration_isolated','Phase 12 remained dormant','p11_formal_acceptance_required','p11_merge_authorization_required')){if(-not$Text.Contains($Marker)){throw "negative: PhaseMerge missing required P11-999 marker $Marker"}}
$Tokens=$null;$Errors=$null;$Ast=[Management.Automation.Language.Parser]::ParseFile($Script,[ref]$Tokens,[ref]$Errors);$WindowFunction=$Ast.Find({param($Node)$Node-is[Management.Automation.Language.FunctionDefinitionAst]-and$Node.Name-ceq'Get-P10MergeObservationWindowState'},$true);if($Errors.Count-ne0-or$null-eq$WindowFunction){throw 'negative: PhaseMerge observation-window validator AST is unavailable'};Invoke-Expression $WindowFunction.Extent.Text
$Plan=[pscustomobject]@{minimum_nonoverlap_observation_hours=744;windows_must_be_nonoverlapping=$true;window_started_at_field='window_started_at';window_ended_at_field='window_ended_at';duration_field='observed_hours';duration_tolerance_hours=0.01;timestamp_offset_required=$true;insufficient_total_observation_action='extend_current_gate';stop_rules_remain_active_during_extension=$true;minimum_adopted_runs=@(50,100,250,500,1000);minimum_observation_hours=@(24,48,72,120,168)};$Percents=@(1,5,20,50,100);$Samples=@(50,100,250,500,1000);$RequiredHours=@(24,48,72,120,168);$ObservedHours=@(24,48,72,120,480);$Start=[DateTimeOffset]::Parse('2026-01-01T00:00:00Z');$Gates=@();for($Index=0;$Index-lt5;$Index++){$End=$Start.AddHours($ObservedHours[$Index]);$Gates+=[pscustomobject]@{percent=$Percents[$Index];required_adopted_runs=$Samples[$Index];observed_adopted_runs=$Samples[$Index];required_hours=$RequiredHours[$Index];observed_hours=$ObservedHours[$Index];window_started_at=$Start.ToString('o');window_ended_at=$End.ToString('o');satisfied=$true;all_risk_slices_observed=$true;timer_restarted_on_transition=$true};$Start=$End};$WindowState=Get-P10MergeObservationWindowState -Rollout ([pscustomobject]@{gates=$Gates}) -Plan $Plan;if(-not[bool]$WindowState.passed){throw 'positive: PhaseMerge rejected exact 744-hour non-overlapping observation'};$Gates[4].observed_hours=479;$Gates[4].window_ended_at=([DateTimeOffset]::Parse([string]$Gates[4].window_started_at)).AddHours(479).ToString('o');$ShortState=Get-P10MergeObservationWindowState -Rollout ([pscustomobject]@{gates=$Gates}) -Plan $Plan;if([bool]$ShortState.passed-or[int]$ShortState.checks.minimum_total_observation_failure_count-ne1){throw 'negative: PhaseMerge accepted 743 observed hours'}
$AuthorizationFunction=$Ast.Find({param($Node)$Node-is[Management.Automation.Language.FunctionDefinitionAst]-and$Node.Name-ceq'Get-P11MergeAuthorizationState'},$true);if($null-eq$AuthorizationFunction){throw 'negative: P11 merge authorization validator AST is unavailable'};Invoke-Expression $AuthorizationFunction.Extent.Text
$Now=[DateTimeOffset]::Parse('2026-01-02T00:00:00Z');$Candidate='1'*40;$Base='2'*40;$Landing=$Base;$ReceiptHash='a'*64;$GateHash='b'*64;$Approvals=@();foreach($Role in @('Engineering','Product','Security')){$Approvals+=[pscustomobject]@{role=$Role;actor_id="actor-$Role";decision='approved';candidate_head_oid=$Candidate;signed_at='2026-01-01T00:00:00Z';expires_at='2026-01-10T00:00:00Z';conditions_open=0;reviewer_is_implementer=$false;permanent_reference="owner://$Role/decision"}};$Authorization=[pscustomobject]@{schema_version='1.0';task_id='TASK-P11-999';decision='approved';candidate_head_oid=$Candidate;phase_base_oid=$Base;landing_oid=$Landing;approval_tip_rule='current_source_tip_after_approval_only_evidence';acceptance_receipts_sha256=$ReceiptHash;acceptance_gate_sha256=$GateHash;open_p0_p1=0;conditions_open=0;approvals=$Approvals};$AuthorizationState=Get-P11MergeAuthorizationState -Authorization $Authorization -CandidateOid $Candidate -PhaseBaseOid $Base -LandingOid $Landing -AcceptanceReceiptSha256 $ReceiptHash -AcceptanceGateSha256 $GateHash -Now $Now;if(-not[bool]$AuthorizationState.passed){throw 'positive: valid P11 merge authorization was rejected'};$Approvals[0].expires_at='2026-01-01T12:00:00Z';$ExpiredState=Get-P11MergeAuthorizationState -Authorization $Authorization -CandidateOid $Candidate -PhaseBaseOid $Base -LandingOid $Landing -AcceptanceReceiptSha256 $ReceiptHash -AcceptanceGateSha256 $GateHash -Now $Now;if([bool]$ExpiredState.passed-or[int]$ExpiredState.checks.approval_expired-ne1){throw 'negative: expired P11 merge authorization was accepted'}
if($Text -match'(?i)(git\s+(?:reset\s+--hard|clean\s+-fdx|push\s+--force))'){throw 'negative: destructive rollback command present'}
exit 0
