$ErrorActionPreference = 'Stop'
$Script = Join-Path (Split-Path -Parent $PSScriptRoot) 'Invoke-PhaseMerge.ps1'
$Text = Get-Content -LiteralPath $Script -Raw -Encoding UTF8
& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $Script -SelfTest
if ($LASTEXITCODE -ne 0) { throw 'positive self-test failed' }
& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $Script -Mode 'Unknown'
if ($LASTEXITCODE -eq 0) { throw 'negative unknown mode was accepted' }
$Root = (Resolve-Path (Join-Path $PSScriptRoot '..\..\..\..')).Path
& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $Script -TaskId 'TASK-P10-999' -ControlRepo $Root -SourceWorktree $Root -LandingEvidenceRoot (Join-Path $Root 'docs/execution/evidence') -Mode 'Cleanup'
if ($LASTEXITCODE -eq 0) { throw 'negative missing cross-shell state was accepted' }
$Tokens=$null;$Errors=$null;$Ast=[Management.Automation.Language.Parser]::ParseFile($Script,[ref]$Tokens,[ref]$Errors);if($Errors.Count-ne0){throw 'negative: PhaseMerge parser errors detected'}
foreach($Marker in @('TASK-P10-999','Invoke-P10MergePreflight','p10_999_formal_preflight_failed','approval_only_diff_invalid','governance_receipt_valid','P10-009/personal-release-certification.json','P10-010/automated-acceptance-attestation.json','P10-010/owner-canary-report.json','p10_009_attestation_sha256','p10_010_attestation_sha256','owner_canary_invalid','Get-PersonalMergeAuthorizationState','owner_directive_plus_automated_attestation','merge-authorization.json','git merge --no-ff --no-edit','Push-Location -LiteralPath $LandingRoot','parent_count','approval_tip_tree','Invoke-IntegrationSmoke.ps1','smoke_attestation_oid','within_48_hours','manifest_self_reference_count','phase_close_chain_valid','Invoke-MergeModePush','git -C $ControlRepo push --atomic --porcelain origin','phase_remote_oid','landing_remote_oid','unexpected_remote_ref_writes','p10_999_push_receipt_conflict','reviewer_independent=$false','valid_secret_finding_count','identity_denied_mismatch','authorization_bypass_count','non-force revert PR')){if(-not$Text.Contains($Marker)){throw "negative: PhaseMerge missing required personal P10-999 marker $Marker"}}
foreach($Marker in @('TASK-P11-999','Invoke-P11MergePreflight','p11_999_formal_preflight_failed','codex/phase-11-rag','P11-990/personal-acceptance-attestation.json','P11-990/rollback-drill.local.json','P11-999/merge-authorization.json','owner_directive_plus_automated_attestation','personal_automated','architecture_hash_mismatch','reviewer_independent=$false','attestation_sha256','parallel_phase12_ref_count','acceptance_gate_invalid','merge_authorization_hash_mismatch','environment_class-ceq''local_isolated''','production_same_configuration_executed','formal_rollback_status-ceq''pending_external''','Phase 12 remained dormant','p11_formal_acceptance_required','p11_merge_authorization_required')){if(-not$Text.Contains($Marker)){throw "negative: PhaseMerge missing required personal P11-999 marker $Marker"}}
$P10Preflight=$Ast.Find({param($Node)$Node-is[Management.Automation.Language.FunctionDefinitionAst]-and$Node.Name-ceq'Invoke-P10MergePreflight'},$true);if($null-eq$P10Preflight-or$P10Preflight.Extent.Text-cmatch'Get-P10MergeObservationWindowState|minimum_nonoverlap_observation_hours|rollout_artifact_hash_mismatch'){throw 'negative: personal P10 merge preflight still depends on the inactive enterprise 744-hour observation contract'}
$GenericAuthorizationFunction=$Ast.Find({param($Node)$Node-is[Management.Automation.Language.FunctionDefinitionAst]-and$Node.Name-ceq'Get-PersonalMergeAuthorizationState'},$true);$P11AuthorizationFunction=$Ast.Find({param($Node)$Node-is[Management.Automation.Language.FunctionDefinitionAst]-and$Node.Name-ceq'Get-P11MergeAuthorizationState'},$true);if($null-eq$GenericAuthorizationFunction-or$null-eq$P11AuthorizationFunction){throw 'negative: personal merge authorization validators are unavailable'};Invoke-Expression $GenericAuthorizationFunction.Extent.Text;Invoke-Expression $P11AuthorizationFunction.Extent.Text
$Candidate='1'*40;$ApprovalTip='3'*40;$Base='2'*40;$Landing=$Base;$AttestationHash='a'*64;$GateHash='b'*64;$GovernanceHash='c'*64
foreach($ExpectedTaskId in @('TASK-P10-999','TASK-P11-999')){$Authorization=[pscustomobject]@{schema_version='1.0';task_id=$ExpectedTaskId;profile='personal_automated';authorization_method='owner_directive_plus_automated_attestation';decision='approved_for_exact_non_force_landing_merge';candidate_head_oid=$Candidate;approval_tip_oid=$ApprovalTip;phase_base_oid=$Base;landing_oid=$Landing;acceptance_attestation_sha256=$AttestationHash;acceptance_gate_sha256=$GateHash;governance_adoption_sha256=$GovernanceHash;open_p0_p1=0;conditions_open=0;production_write_count=0;remote_write_count=0};$AuthorizationState=Get-PersonalMergeAuthorizationState -Authorization $Authorization -CandidateOid $Candidate -ApprovalTipOid $ApprovalTip -PhaseBaseOid $Base -LandingOid $Landing -AcceptanceAttestationSha256 $AttestationHash -AcceptanceGateSha256 $GateHash -GovernanceSha256 $GovernanceHash -ExpectedTaskId $ExpectedTaskId;if(-not[bool]$AuthorizationState.passed){throw "positive: exact personal automated authorization was rejected for $ExpectedTaskId"};$Authorization.acceptance_attestation_sha256='d'*64;$TamperedState=Get-PersonalMergeAuthorizationState -Authorization $Authorization -CandidateOid $Candidate -ApprovalTipOid $ApprovalTip -PhaseBaseOid $Base -LandingOid $Landing -AcceptanceAttestationSha256 $AttestationHash -AcceptanceGateSha256 $GateHash -GovernanceSha256 $GovernanceHash -ExpectedTaskId $ExpectedTaskId;if([bool]$TamperedState.passed-or[int]$TamperedState.checks.approval_record_invalid-ne1){throw "negative: $ExpectedTaskId authorization accepted a tampered automated attestation binding"}}
if($Text -match'(?i)(git\s+(?:reset\s+--hard|clean\s+-fdx|push\s+--force))'){throw 'negative: destructive rollback command present'}
exit 0
