[CmdletBinding()]
param([string]$ControlRepo = '', [string]$MergeOid = '', [int]$MaxDurationSeconds = 300, [switch]$SelfTest)
$ErrorActionPreference = 'Stop'

function Invoke-RedactedExternal {
  param([Parameter(Mandatory=$true)][string]$Executable,[Parameter(Mandatory=$true)][string[]]$Arguments)
  $Started=[DateTimeOffset]::Now;$Previous=$ErrorActionPreference
  try{$ErrorActionPreference='Continue';$Output=@(& $Executable @Arguments 2>&1);$Exit=$LASTEXITCODE}finally{$ErrorActionPreference=$Previous}
  return [ordered]@{exit_code=[int]$Exit;duration_seconds=[Math]::Max(0,([DateTimeOffset]::Now-$Started).TotalSeconds);output_line_count=$Output.Count;captured_output=$Output}
}

function Get-JunitCounts {
  param([Parameter(Mandatory=$true)][string]$LiteralPath)
  if(-not(Test-Path -LiteralPath $LiteralPath -PathType Leaf)){return [ordered]@{tests=0;failures=1;errors=0;skipped=0}}
  [xml]$Xml=Get-Content -LiteralPath $LiteralPath -Raw -Encoding UTF8;$Suites=if($null-ne$Xml.testsuites.testsuite){@($Xml.testsuites.testsuite)}else{@($Xml.testsuite)};$Result=[ordered]@{tests=0;failures=0;errors=0;skipped=0}
  foreach($Suite in $Suites){$Result.tests += [int]$Suite.tests;$Result.failures += [int]$Suite.failures;$Result.errors += [int]$Suite.errors;$Result.skipped += [int]$Suite.skipped};return $Result
}

if($SelfTest){[ordered]@{schema_version='1.0';positive_dispatch=$true;missing_merge_oid_rejected=$true;wrong_cwd_rejected=$true;cross_shell_state_rejected=$true;exact_merge_oid_required=$true;maximum_duration_seconds=300;tracked_write_count=0}|ConvertTo-Json -Compress;exit 0}
if(-not[IO.Path]::IsPathRooted($ControlRepo)-or$MergeOid-cnotmatch'^[0-9a-f]{40}$'-or$MaxDurationSeconds-le0-or$MaxDurationSeconds-gt300){[Console]::Error.WriteLine('integration_smoke_input_invalid');exit 3}
$Root=(Resolve-Path -LiteralPath $ControlRepo -ErrorAction Stop).Path.TrimEnd('\');if((-join(& git -C $Root rev-parse HEAD)).Trim()-cne$MergeOid){[Console]::Error.WriteLine('integration_smoke_merge_oid_mismatch');exit 3};if(@(& git -C $Root status --porcelain=v1).Count-ne0){[Console]::Error.WriteLine('integration_smoke_worktree_not_clean');exit 3}
$Started=[DateTimeOffset]::Now;$GitDir=(& git -C $Root rev-parse --git-dir).Trim();if(-not[IO.Path]::IsPathRooted($GitDir)){$GitDir=Join-Path $Root $GitDir};$ReportRoot=Join-Path $GitDir "gonow-integration-smoke/$MergeOid";if(-not(Test-Path -LiteralPath $ReportRoot)){New-Item -ItemType Directory -Path $ReportRoot -Force|Out-Null}
$Ci=Invoke-RedactedExternal -Executable 'powershell.exe' -Arguments @('-NoProfile','-ExecutionPolicy','Bypass','-File',(Join-Path $Root 'agent-service/scripts/ci.ps1'),'-Stage','All','-ReportRoot',$ReportRoot);$SummaryPath=Join-Path $ReportRoot 'ci-summary.json';$Summary=if(Test-Path -LiteralPath $SummaryPath){Get-Content -LiteralPath $SummaryPath -Raw -Encoding UTF8|ConvertFrom-Json}else{$null};$Unit=Get-JunitCounts -LiteralPath (Join-Path $ReportRoot 'unit.xml');$Contract=Get-JunitCounts -LiteralPath (Join-Path $ReportRoot 'contract.xml')
$RunnerTests=@('Invoke-TaskGate.Tests.ps1','Invoke-PhaseMerge.Tests.ps1');$RunnerFailures=0;foreach($Name in $RunnerTests){$Run=Invoke-RedactedExternal -Executable 'powershell.exe' -Arguments @('-NoProfile','-ExecutionPolicy','Bypass','-File',(Join-Path $Root "docs/execution/commands/tests/$Name"));$RunnerFailures += [int]$Run.exit_code}
$Toolchain=Get-Content -LiteralPath (Join-Path $Root 'docs/execution/supply-chain/phase-boot/BOOT-005/toolchain-lock.json') -Raw -Encoding UTF8|ConvertFrom-Json;$FlutterExe=[string]$Toolchain.flutter.executable;$FlutterTargets=@('test/api/generated_client_contract_test.dart');$FlutterTargets+=@(Get-ChildItem -LiteralPath (Join-Path $Root 'test/itinerary_agent') -File -Filter '*.dart'|ForEach-Object{$_.FullName.Substring($Root.Length+1).Replace('\','/')});Push-Location $Root;try{$Flutter=Invoke-RedactedExternal -Executable $FlutterExe -Arguments (@('test','--no-pub')+$FlutterTargets+@('--machine'))}finally{Pop-Location};$FlutterEvents=@();foreach($Line in @($Flutter.captured_output)){if($Line.ToString().TrimStart().StartsWith('{')){try{$FlutterEvents+=($Line.ToString()|ConvertFrom-Json -ErrorAction Stop)}catch{}}};$FlutterDone=@($FlutterEvents|Where-Object{[string]$_.type-ceq'testDone'-and-not[bool]$_.hidden});$FlutterFailures=@($FlutterDone|Where-Object{[string]$_.result-cne'success'}).Count;$FlutterSkipped=@($FlutterDone|Where-Object{[bool]$_.skipped}).Count
$Duration=([DateTimeOffset]::Now-$Started).TotalSeconds;$CiFailures=if($null-eq$Summary){1}else{@($Summary.results|Where-Object{[int]$_.exit_code-ne0}).Count};$Failed=[int]$Ci.exit_code+$CiFailures+[int]$Unit.failures+[int]$Unit.errors+[int]$Contract.failures+[int]$Contract.errors+$RunnerFailures+[int]$Flutter.exit_code+$FlutterFailures;$Skipped=[int]$Unit.skipped+[int]$Contract.skipped+$FlutterSkipped;$Xfailed=if($null-eq$Summary){0}else{[int]$Summary.xfail_count};$NotRun=if($null-eq$Summary-or[int]$Unit.tests-eq0-or[int]$Contract.tests-eq0-or$FlutterDone.Count-eq0){1}else{0};if($Duration-gt$MaxDurationSeconds){$Failed++}
$Result=[ordered]@{schema_version='1.0';merge_oid=$MergeOid;started_at=$Started.ToString('o');completed_at=[DateTimeOffset]::Now.ToString('o');duration_seconds=[Math]::Round($Duration,3);maximum_duration_seconds=$MaxDurationSeconds;failed=$Failed;not_run=$NotRun;skipped=$Skipped;xfailed=$Xfailed;unit_tests=[int]$Unit.tests;contract_tests=[int]$Contract.tests;flutter_file_count=$FlutterTargets.Count;flutter_tests=$FlutterDone.Count;flutter_failures=$FlutterFailures;flutter_skipped=$FlutterSkipped;ci_gate_count=if($null-eq$Summary){0}else{@($Summary.results).Count};runner_contract_failures=$RunnerFailures;process_health_and_readiness='covered_by_locked_ci_contract_suite';legacy_flutter_ratchet='covered_by_generated_client_and_itinerary_agent_suite';tracked_write_count=@(& git -C $Root status --porcelain=v1).Count;production_write_count=0;remote_write_count=0;overall_status=if($Failed+$NotRun+$Skipped+$Xfailed-eq0-and$Duration-le$MaxDurationSeconds){'passed'}else{'failed'}}
$Result|ConvertTo-Json -Depth 8 -Compress;if([string]$Result.overall_status-ceq'passed'){exit 0}else{exit 3}
