[CmdletBinding()]
param(
  [string]$TaskId = '', [string]$ControlRepo = '', [string]$SourceWorktree = '',
  [string]$SourceBranch = '', [string]$LandingBranch = 'codex/gonow-agent-landing',
  [string]$LandingEvidenceRoot = '', [string]$Mode = '', [int]$MaxDurationSeconds = 300,
  [switch]$SelfTest
)
$ErrorActionPreference = 'Stop'
$ModeNames = @('MergePreflight','Cleanup','Merge','MergeTreeVerification','IntegrationSmoke','PostMergeEvidence','Retrospective','Archive','CloseVerify','Security','RollbackVerify')

function Get-Sha256 {param([Parameter(Mandatory=$true)][string]$LiteralPath);return (Get-FileHash -Algorithm SHA256 -LiteralPath $LiteralPath).Hash.ToLowerInvariant()}
function Get-StringSha256 {param([Parameter(Mandatory=$true)][string]$Value);$Hasher=[Security.Cryptography.SHA256]::Create();try{return ([BitConverter]::ToString($Hasher.ComputeHash([Text.Encoding]::UTF8.GetBytes($Value)))).Replace('-','').ToLowerInvariant()}finally{$Hasher.Dispose()}}
function Get-GitOid {param([Parameter(Mandatory=$true)][string]$Repository,[Parameter(Mandatory=$true)][string]$Revision);$Value=(& git -C $Repository rev-parse $Revision 2>$null)-join'';if($LASTEXITCODE-ne0){return ''};return $Value.Trim()}
function Write-AtomicJson {
  param([Parameter(Mandatory=$true)][string]$LiteralPath,[Parameter(Mandatory=$true)]$Value)
  $Directory=Split-Path -Parent $LiteralPath;if(-not(Test-Path -LiteralPath $Directory)){New-Item -ItemType Directory -Path $Directory -Force|Out-Null};$Temp=Join-Path $Directory ('.'+[IO.Path]::GetFileName($LiteralPath)+'.'+[Guid]::NewGuid().ToString('N')+'.tmp');[IO.File]::WriteAllText($Temp,(($Value|ConvertTo-Json -Depth 30)+"`n"),[Text.UTF8Encoding]::new($false));Move-Item -LiteralPath $Temp -Destination $LiteralPath -Force
}
function Write-AtomicText {param([Parameter(Mandatory=$true)][string]$LiteralPath,[Parameter(Mandatory=$true)][string]$Text);$Directory=Split-Path -Parent $LiteralPath;if(-not(Test-Path -LiteralPath $Directory)){New-Item -ItemType Directory -Path $Directory -Force|Out-Null};$Temp=Join-Path $Directory ('.'+[IO.Path]::GetFileName($LiteralPath)+'.'+[Guid]::NewGuid().ToString('N')+'.tmp');[IO.File]::WriteAllText($Temp,$Text,[Text.UTF8Encoding]::new($false));Move-Item -LiteralPath $Temp -Destination $LiteralPath -Force}
function New-MergeResult {param([string]$ModeName,[string]$Status,[string]$ReasonCode,$Checks);return [ordered]@{schema_version='1.0';task_id=$TaskId;mode=$ModeName;status=$Status;reason_code=$ReasonCode;checks=$Checks;landing_write_count=0;remote_write_count=0;recorded_at=[DateTimeOffset]::Now.ToString('o')}}
function New-BlockedMergeResult {param([string]$ModeName,[string]$ReasonCode,$Checks=@{});return New-MergeResult $ModeName 'blocked' $ReasonCode $Checks}
function New-PassedMergeResult {param([string]$ModeName,$Checks);return New-MergeResult $ModeName 'passed' '' $Checks}
function Set-ObjectProperty {param($Object,[string]$Name,$Value);if($null-ne$Object.PSObject.Properties[$Name]){$Object.$Name=$Value}else{$Object|Add-Member -NotePropertyName $Name -NotePropertyValue $Value}}
function Read-MergeState {if(-not(Test-Path -LiteralPath $script:StatePath -PathType Leaf)){return $null};try{return Get-Content -LiteralPath $script:StatePath -Raw -Encoding UTF8|ConvertFrom-Json -ErrorAction Stop}catch{return $null}}
function Write-MergeState {param($State);Write-AtomicJson -LiteralPath $script:StatePath -Value $State}
function Test-ModePassed {param($State,[string]$ModeName);if($null-eq$State){return $false};$Rows=@($State.history|Where-Object{[string]$_.mode-ceq$ModeName});return $Rows.Count-ge1-and[string]$Rows[-1].status-ceq'passed'}
function Save-ModeResult {param($Result);$State=Read-MergeState;if($null-eq$State){return};$History=@($State.history);$History+=[ordered]@{mode=$Result.mode;status=$Result.status;reason_code=$Result.reason_code;checks=$Result.checks;recorded_at=$Result.recorded_at};Set-ObjectProperty $State 'history' $History;Set-ObjectProperty $State 'last_mode' $Result.mode;Set-ObjectProperty $State 'last_status' $Result.status;Set-ObjectProperty $State 'updated_at' ([DateTimeOffset]::Now.ToString('o'));Write-MergeState $State}
function Get-LandingWorktree {
  $Lines=@(& git -C $ControlRepo worktree list --porcelain);$Path='';$Branch='';foreach($Line in $Lines){if($Line.StartsWith('worktree ')){$Path=$Line.Substring(9).Trim();$Branch=''}elseif($Line.StartsWith('branch ')){$Branch=$Line.Substring(7).Trim();if($Branch-ceq"refs/heads/$LandingBranch"){return $Path}}};if((Get-GitOid $ControlRepo 'HEAD')-and((& git -C $ControlRepo symbolic-ref --short HEAD 2>$null)-join'').Trim()-ceq$LandingBranch){return $ControlRepo};return ''
}
function Test-FrozenState {
  param($State,[switch]$AfterMerge)
  if($null-eq$State){return $false};if($SourceWorktree.TrimEnd('\')-cne([string]$State.source_worktree).TrimEnd('\')-or$SourceBranch-cne[string]$State.source_branch-or$LandingBranch-cne[string]$State.landing_branch-or$LandingEvidenceRoot.TrimEnd('\')-cne([string]$State.requested_landing_evidence_root).TrimEnd('\')){return $false};if((Get-GitOid $SourceWorktree $SourceBranch)-cne[string]$State.approval_tip_oid){return $false};if(-not$AfterMerge-and(Get-GitOid $ControlRepo "refs/heads/$LandingBranch")-cne[string]$State.phase_base_oid){return $false};if($AfterMerge-and[string]$State.merge_oid-cnotmatch'^[0-9a-f]{40}$'){return $false};return $true
}
function Get-P10MergeObservationWindowState {
  param([AllowNull()][object]$Rollout,[AllowNull()][object]$Plan)
  $Percents=@(1,5,20,50,100);$Samples=@(50,100,250,500,1000);$Hours=@(24,48,72,120,168);$Gates=if($null-ne$Rollout){@($Rollout.gates)}else{@()};$PlanFailures=if($null-ne$Plan-and[int]$Plan.minimum_nonoverlap_observation_hours-eq744-and[bool]$Plan.windows_must_be_nonoverlapping-and[string]$Plan.window_started_at_field-ceq'window_started_at'-and[string]$Plan.window_ended_at_field-ceq'window_ended_at'-and[string]$Plan.duration_field-ceq'observed_hours'-and[double]$Plan.duration_tolerance_hours-eq0.01-and[bool]$Plan.timestamp_offset_required-and[string]$Plan.insufficient_total_observation_action-ceq'extend_current_gate'-and[bool]$Plan.stop_rules_remain_active_during_extension-and(@($Plan.minimum_adopted_runs)-join',')-ceq($Samples-join',')-and(@($Plan.minimum_observation_hours)-join',')-ceq($Hours-join',')){0}else{1};$ContractFailures=if($Gates.Count-eq5){0}else{1};$ParseFailures=0;$OffsetFailures=0;$NonOverlapFailures=0;$DurationFailures=0;$SatisfactionFailures=0;$Total=0.0;$PreviousEnd=$null
  for($Index=0;$Index-lt$Gates.Count;$Index++){$Gate=$Gates[$Index];if($Index-ge5-or[int]$Gate.percent-ne$Percents[$Index]-or[int]$Gate.required_adopted_runs-ne$Samples[$Index]-or[double]$Gate.required_hours-ne$Hours[$Index]){$ContractFailures++};if(-not[bool]$Gate.satisfied-or-not[bool]$Gate.all_risk_slices_observed-or[int]$Gate.observed_adopted_runs-lt[int]$Gate.required_adopted_runs-or[double]$Gate.observed_hours-lt[double]$Gate.required_hours-or-not[bool]$Gate.timer_restarted_on_transition){$SatisfactionFailures++};$StartText=[string]$Gate.window_started_at;$EndText=[string]$Gate.window_ended_at;if($StartText-cnotmatch'(?:Z|[+-][0-9]{2}:[0-9]{2})$'-or$EndText-cnotmatch'(?:Z|[+-][0-9]{2}:[0-9]{2})$'){$OffsetFailures++};try{$Start=[DateTimeOffset]::Parse($StartText,[Globalization.CultureInfo]::InvariantCulture);$End=[DateTimeOffset]::Parse($EndText,[Globalization.CultureInfo]::InvariantCulture)}catch{$ParseFailures++;continue};if($End-le$Start){$DurationFailures++;continue};if($null-ne$PreviousEnd-and$Start-lt$PreviousEnd){$NonOverlapFailures++};$Observed=[double]$Gate.observed_hours;$Total+=$Observed;if([Math]::Abs(($End-$Start).TotalHours-$Observed)-gt0.01){$DurationFailures++};$PreviousEnd=$End}
  $Checks=[ordered]@{minimum_nonoverlap_observation_hours=744;observed_nonoverlap_hours=[Math]::Round($Total,3);plan_contract_failure_count=$PlanFailures;gate_contract_failure_count=$ContractFailures;gate_satisfaction_failure_count=$SatisfactionFailures;timestamp_parse_failure_count=$ParseFailures;timestamp_offset_failure_count=$OffsetFailures;nonoverlap_failure_count=$NonOverlapFailures;duration_binding_failure_count=$DurationFailures;minimum_total_observation_failure_count=if($Total+0.01-lt744){1}else{0}}
  $Failure=[int]$Checks.plan_contract_failure_count+[int]$Checks.gate_contract_failure_count+[int]$Checks.gate_satisfaction_failure_count+[int]$Checks.timestamp_parse_failure_count+[int]$Checks.timestamp_offset_failure_count+[int]$Checks.nonoverlap_failure_count+[int]$Checks.duration_binding_failure_count+[int]$Checks.minimum_total_observation_failure_count;return [ordered]@{passed=($Failure-eq0);checks=$Checks}
}

function Get-PhaseMergeProfile {
  if ($TaskId -ceq 'TASK-P10-999') {
    return [ordered]@{
      task_id='TASK-P10-999'; prefix='p10_999'; phase_name='Phase 10'; phase_slug='phase-10'
      task_slug='P10-999'; acceptance_slug='P10-990'; source_branch='codex/phase-10-release-b-gates'
      regression_path='docs/execution/evidence/phase-10/P10-990/regression-summary.json'
      decision_reference='docs/execution/evidence/phase-10/P10-999/merge-authorization.json'
      smoke_commit_subject='evidence: attest Phase 10 integration smoke'; close_commit_subject='evidence: close Phase 10'
    }
  }
  if ($TaskId -ceq 'TASK-P11-999') {
    return [ordered]@{
      task_id='TASK-P11-999'; prefix='p11_999'; phase_name='Phase 11'; phase_slug='phase-11'
      task_slug='P11-999'; acceptance_slug='P11-990'; source_branch='codex/phase-11-rag'
      regression_path='docs/execution/evidence/phase-11/P11-990/regression-summary.json'
      decision_reference='docs/execution/evidence/phase-11/P11-999/merge-authorization.json'
      smoke_commit_subject='evidence: attest Phase 11 integration smoke'; close_commit_subject='evidence: close Phase 11'
    }
  }
  return $null
}

function Read-JsonFileOrNull {
  param([Parameter(Mandatory=$true)][string]$LiteralPath)
  if (-not (Test-Path -LiteralPath $LiteralPath -PathType Leaf)) { return $null }
  try { return Get-Content -LiteralPath $LiteralPath -Raw -Encoding UTF8 | ConvertFrom-Json -ErrorAction Stop } catch { return $null }
}

function Get-GateResultDetail {
  param([AllowNull()][object]$Gate,[Parameter(Mandatory=$true)][string]$ModeName)
  if ($null -eq $Gate) { return $null }
  $Rows=@($Gate.results|Where-Object{[string]$_.check_id-ceq$ModeName-and[string]$_.status-ceq'passed'})
  if ($Rows.Count -ne 1) { return $null }
  try { return [string]$Rows[0].detail | ConvertFrom-Json -ErrorAction Stop } catch { return $null }
}

function Get-PersonalGovernanceState {
  param([Parameter(Mandatory=$true)][string]$RepositoryRoot)
  $RelativePath='docs/execution/evidence/governance/personal-automation-adoption-v1.json';$Path=Join-Path $RepositoryRoot $RelativePath;$Receipt=Read-JsonFileOrNull $Path;$Checks=[ordered]@{receipt_missing=if($null-eq$Receipt){1}else{0};schema_invalid=0;document_hash_mismatch=0;architecture_hash_mismatch=0;decision_commit_invalid=0;remote_mismatch=0}
  if($null-ne$Receipt){if([string]$Receipt.schema_version-cne'1.0'-or[string]$Receipt.profile-cne'personal_automated'-or[string]$Receipt.status-cne'adopted_by_repository_owner_directive'){$Checks.schema_invalid=1};foreach($Binding in @($Receipt.documents.agents,$Receipt.documents.execplan,$Receipt.documents.decision_adr)){$Full=Join-Path $RepositoryRoot ([string]$Binding.path);if(-not(Test-Path -LiteralPath $Full -PathType Leaf)-or(Get-Sha256 $Full)-cne[string]$Binding.sha256){$Checks.document_hash_mismatch++}};if([string]$Receipt.documents.architecture.version-cne'1.6.1'-or[string]$Receipt.documents.architecture.sha256-cne'644ab9f5ad04a65383bb34b6628b49472d9f68b50fa3681aa46671f59794c3a6'){$Checks.architecture_hash_mismatch=1};$Commit=[string]$Receipt.decision_source.governance_content_commit_oid;& git -C $RepositoryRoot cat-file -e "$Commit^{commit}" 2>$null;if($LASTEXITCODE-ne0){$Checks.decision_commit_invalid=1}else{& git -C $RepositoryRoot merge-base --is-ancestor $Commit HEAD 2>$null;if($LASTEXITCODE-ne0){$Checks.decision_commit_invalid=1}};$Remote=((& git -C $RepositoryRoot remote get-url origin 2>$null)-join'').Trim();if($LASTEXITCODE-ne0-or$Remote-cne[string]$Receipt.repository.remote){$Checks.remote_mismatch=1}}
  $Failure=0;foreach($Value in $Checks.Values){$Failure+=[int]$Value};return [ordered]@{passed=($Failure-eq0);profile=if($Failure-eq0){'personal_automated'}else{'unknown'};receipt=$Receipt;receipt_path=$RelativePath;receipt_sha256=if(Test-Path -LiteralPath $Path -PathType Leaf){Get-Sha256 $Path}else{''};checks=$Checks}
}

function Get-PersonalMergeAuthorizationState {
  param(
    [AllowNull()][object]$Authorization,[string]$CandidateOid,[string]$ApprovalTipOid,[string]$PhaseBaseOid,
    [string]$LandingOid,[string]$AcceptanceAttestationSha256,[string]$AcceptanceGateSha256,[string]$GovernanceSha256,
    [Parameter(Mandatory=$true)][string]$ExpectedTaskId
  )
  $Valid=$null-ne$Authorization-and[string]$Authorization.schema_version-ceq'1.0'-and[string]$Authorization.task_id-ceq$ExpectedTaskId-and[string]$Authorization.profile-ceq'personal_automated'-and[string]$Authorization.authorization_method-ceq'owner_directive_plus_automated_attestation'-and[string]$Authorization.decision-ceq'approved_for_exact_non_force_landing_merge'-and[string]$Authorization.candidate_head_oid-ceq$CandidateOid-and[string]$Authorization.approval_tip_oid-ceq$ApprovalTipOid-and[string]$Authorization.phase_base_oid-ceq$PhaseBaseOid-and[string]$Authorization.landing_oid-ceq$LandingOid-and[string]$Authorization.acceptance_attestation_sha256-ceq$AcceptanceAttestationSha256-and[string]$Authorization.acceptance_gate_sha256-ceq$AcceptanceGateSha256-and[string]$Authorization.governance_adoption_sha256-ceq$GovernanceSha256-and[int]$Authorization.open_p0_p1+[int]$Authorization.conditions_open+[int]$Authorization.production_write_count+[int]$Authorization.remote_write_count-eq0
  $Checks=[ordered]@{authorization_valid=$Valid;automated_attestation_bound=if($Valid){1}else{0};approval_count=0;required_role_missing=0;approval_record_invalid=if($Valid){0}else{1};approval_expired=0;approval_oid_mismatch=if($Valid){0}else{1};conditional_approval_open_count=if($null-ne$Authorization){[int]$Authorization.conditions_open}else{1};independent_identity_invalid=0}
  return [ordered]@{passed=$Valid;checks=$Checks}
}

function Get-P11MergeAuthorizationState {
  param([AllowNull()][object]$Authorization,[string]$CandidateOid,[string]$ApprovalTipOid,[string]$PhaseBaseOid,[string]$LandingOid,[string]$AcceptanceAttestationSha256,[string]$AcceptanceGateSha256,[string]$GovernanceSha256)
  return Get-PersonalMergeAuthorizationState -Authorization $Authorization -CandidateOid $CandidateOid -ApprovalTipOid $ApprovalTipOid -PhaseBaseOid $PhaseBaseOid -LandingOid $LandingOid -AcceptanceAttestationSha256 $AcceptanceAttestationSha256 -AcceptanceGateSha256 $AcceptanceGateSha256 -GovernanceSha256 $GovernanceSha256 -ExpectedTaskId 'TASK-P11-999'
}

function Invoke-P11MergePreflight {
  $Checks=[ordered]@{acceptance_valid=$false;open_p0_p1=1;approval_expired=0;source_worktree_clean=$false;approval_only_diff_invalid=1;landing_matches_phase_base=$false;governance_receipt_valid=$false;acceptance_gate_invalid=1;required_role_missing=0;independent_identity_invalid=0;approval_record_invalid=1;approval_oid_invalid=1;conditional_approval_open_count=0;parallel_phase12_ref_count=1}
  if($SourceBranch-cne'codex/phase-11-rag'-or$LandingBranch-cne'codex/gonow-agent-landing'){return New-BlockedMergeResult 'MergePreflight' 'p11_999_branch_contract_mismatch' $Checks}
  $SourceRoot=(Resolve-Path -LiteralPath $SourceWorktree -ErrorAction Stop).Path.TrimEnd('\')
  $StatusPath=Join-Path $SourceRoot 'docs/execution/status/TASK-P11-990.json';$AttestationPath=Join-Path $SourceRoot 'docs/execution/evidence/phase-11/P11-990/personal-acceptance-attestation.json';$ManifestPath=Join-Path $SourceRoot 'docs/execution/evidence/phase-11/phase-runtime-manifest.json';$GatePath=Join-Path $SourceRoot 'docs/execution/evidence/phase-11/P11-990/gate-results.json';$GateSummaryPath=Join-Path $SourceRoot 'docs/execution/evidence/phase-11/P11-990/gate-summary.json';$PremergePath=Join-Path $SourceRoot 'docs/execution/evidence/phase-11/artifact-manifest.premerge.json';$ReleaseCertificationPath=Join-Path $SourceRoot 'docs/execution/evidence/phase-10/P10-009/personal-release-certification.json'
  $Required=@($StatusPath,$AttestationPath,$ManifestPath,$GatePath,$GateSummaryPath,$PremergePath,$ReleaseCertificationPath);if(@($Required|Where-Object{-not(Test-Path -LiteralPath $_ -PathType Leaf)}).Count-ne0){return New-BlockedMergeResult 'MergePreflight' 'p11_999_formal_input_missing' $Checks}
  $Status=Read-JsonFileOrNull $StatusPath;$Attestation=Read-JsonFileOrNull $AttestationPath;$Manifest=Read-JsonFileOrNull $ManifestPath;$Gate=Read-JsonFileOrNull $GatePath;$GateSummary=Read-JsonFileOrNull $GateSummaryPath;$ReleaseCertification=Read-JsonFileOrNull $ReleaseCertificationPath;$Governance=Get-PersonalGovernanceState -RepositoryRoot $SourceRoot
  if(@(@($Status,$Attestation,$Manifest,$Gate,$GateSummary,$ReleaseCertification)|Where-Object{$null-eq$_}).Count-ne0-or-not[bool]$Governance.passed){return New-BlockedMergeResult 'MergePreflight' 'p11_999_formal_input_invalid' $Checks}
  $Candidate=[string]$Attestation.candidate_head_oid;$PhaseBase=[string]$Manifest.phase_base_oid;$LandingOid=Get-GitOid $ControlRepo "refs/heads/$LandingBranch";$ApprovalTip=Get-GitOid $SourceRoot $SourceBranch;$GateHash=Get-Sha256 $GatePath;$AttestationHash=Get-Sha256 $AttestationPath
  $RequiredAcceptanceModes=@('AcceptancePreflight','ApprovalValidation','BuildAcceptance','Documentation','Evidence','Regression','RollbackDrill','RollbackVerify','Security','Verify');$AcceptanceGateInvalid=@($RequiredAcceptanceModes|Where-Object{$Name=$_;$Rows=@($Gate.results|Where-Object{[string]$_.check_id-ceq$Name-and[string]$_.status-ceq'passed'});$Rows.Count-ne1}).Count
  $AttestationFailure=0;foreach($Value in $Attestation.checks.PSObject.Properties.Value){$AttestationFailure+=[int]$Value};$OpenP0P1=if([string]$Attestation.overall_status-ceq'passed' -and $AttestationFailure-eq0){0}else{1}
  $Authorization=[ordered]@{schema_version='1.0';task_id='TASK-P11-999';profile='personal_automated';authorization_method='owner_directive_plus_automated_attestation';decision='approved_for_exact_non_force_landing_merge';candidate_head_oid=$Candidate;approval_tip_oid=$ApprovalTip;phase_base_oid=$PhaseBase;landing_oid=$LandingOid;acceptance_attestation_sha256=$AttestationHash;acceptance_gate_sha256=$GateHash;governance_adoption_sha256=[string]$Governance.receipt_sha256;open_p0_p1=$OpenP0P1;conditions_open=0;production_write_count=0;remote_write_count=0;generated_at=[DateTimeOffset]::Now.ToString('o')}
  $AuthorizationState=Get-P11MergeAuthorizationState -Authorization $Authorization -CandidateOid $Candidate -ApprovalTipOid $ApprovalTip -PhaseBaseOid $PhaseBase -LandingOid $LandingOid -AcceptanceAttestationSha256 $AttestationHash -AcceptanceGateSha256 $GateHash -GovernanceSha256 ([string]$Governance.receipt_sha256)
  $ApprovalFiles=@(& git -C $SourceRoot diff --name-only $Candidate $ApprovalTip --);$InvalidApprovalFiles=@($ApprovalFiles|Where-Object{$Name=$_.Replace('\','/');$Name-cne'docs/execution/evidence/phase-11/acceptance.md'-and$Name-cne'docs/execution/evidence/index.json'-and$Name-cne'docs/execution/status/TASK-P11-990.json'-and-not$Name.StartsWith('docs/execution/evidence/phase-11/P11-990/',[StringComparison]::Ordinal)})
  & git -C $SourceRoot merge-base --is-ancestor $Candidate $ApprovalTip 2>$null;$AncestorExit=$LASTEXITCODE;$Phase12Refs=@(& git -C $ControlRepo for-each-ref --format='%(refname)' 'refs/heads/codex/phase-12*')
  $Checks.acceptance_valid=[string]$Status.status-ceq'accepted'-and-not[bool]$Status.reviewer_independent-and[string]$Status.governance_profile-ceq'personal_automated'-and[string]$Status.acceptance_method-ceq'automated_attestation'-and[string]$Status.attestation_sha256-ceq$AttestationHash-and[string]$Status.evidence_sha256-ceq$GateHash-and[string]$Status.head_oid-ceq$Candidate-and[string]$Attestation.profile-ceq'personal_automated'-and[string]$Attestation.overall_status-ceq'passed'-and[bool]$Attestation.automated_gate_acceptance-and[bool]$GateSummary.checks.primary_assertion-and[string]$GateSummary.checks.overall_status-ceq'passed'-and[string]$ReleaseCertification.overall_status-ceq'passed'-and[int]$ReleaseCertification.certification_gate_pass_count-eq5
  $Checks.open_p0_p1=$OpenP0P1;$Checks.approval_expired=0;$Checks.source_worktree_clean=@(& git -C $SourceRoot status --porcelain=v1).Count-eq0;$Checks.approval_only_diff_invalid=$InvalidApprovalFiles.Count;$Checks.landing_matches_phase_base=$LandingOid-ceq$PhaseBase;$Checks.governance_receipt_valid=[bool]$Governance.passed;$Checks.acceptance_gate_invalid=$AcceptanceGateInvalid;$Checks.required_role_missing=0;$Checks.independent_identity_invalid=0;$Checks.approval_record_invalid=[int]$AuthorizationState.checks.approval_record_invalid;$Checks.approval_oid_invalid=[int]$AuthorizationState.checks.approval_oid_mismatch+$(if($Candidate-cmatch'^[0-9a-f]{40}$'-and$ApprovalTip-cmatch'^[0-9a-f]{40}$'-and$AncestorExit-eq0){0}else{1});$Checks.conditional_approval_open_count=[int]$AuthorizationState.checks.conditional_approval_open_count;$Checks.parallel_phase12_ref_count=$Phase12Refs.Count
  $Failure=if(-not$Checks.acceptance_valid-or-not$Checks.source_worktree_clean-or-not$Checks.landing_matches_phase_base-or-not$Checks.governance_receipt_valid-or-not[bool]$AuthorizationState.passed){1}else{0};$Failure+=[int]$Checks.open_p0_p1+[int]$Checks.approval_expired+[int]$Checks.approval_only_diff_invalid+[int]$Checks.acceptance_gate_invalid+[int]$Checks.required_role_missing+[int]$Checks.independent_identity_invalid+[int]$Checks.approval_record_invalid+[int]$Checks.approval_oid_invalid+[int]$Checks.conditional_approval_open_count+[int]$Checks.parallel_phase12_ref_count
  $AuthorizationJson=$Authorization|ConvertTo-Json -Depth 20 -Compress;$State=[ordered]@{schema_version='1.0';task_id=$TaskId;source_worktree=$SourceRoot;source_branch=$SourceBranch;landing_branch=$LandingBranch;requested_landing_evidence_root=$LandingEvidenceRoot;phase_base_oid=$PhaseBase;candidate_head_oid=$Candidate;approval_tip_oid=$ApprovalTip;approval_tip_tree=Get-GitOid $SourceRoot "$ApprovalTip^{tree}";landing_premerge_oid=$LandingOid;source_status_sha256=Get-Sha256 $StatusPath;approval_validation_sha256=$AttestationHash;merge_authorization_sha256=Get-StringSha256 $AuthorizationJson;merge_authorization=$Authorization;governance_receipt_sha256=[string]$Governance.receipt_sha256;checks=$Checks;history=@();created_at=[DateTimeOffset]::Now.ToString('o');merge_oid=$null;smoke_attestation_oid=$null;phase_close_oid=$null};Write-MergeState $State
  if($Failure-ne0){return New-BlockedMergeResult 'MergePreflight' 'p11_999_formal_preflight_failed' $Checks};return New-PassedMergeResult 'MergePreflight' $Checks
}

function Invoke-P10MergePreflight {
  $Checks=[ordered]@{acceptance_valid=$false;open_p0_p1=1;approval_expired=0;source_worktree_clean=$false;approval_only_diff_invalid=1;landing_matches_phase_base=$false;governance_receipt_valid=$false;acceptance_gate_invalid=1;required_role_missing=0;independent_identity_invalid=0;approval_record_invalid=1;approval_oid_invalid=1;conditional_approval_open_count=0;owner_canary_invalid=1}
  if($SourceBranch-cne'codex/phase-10-release-b-gates'-or$LandingBranch-cne'codex/gonow-agent-landing'){return New-BlockedMergeResult 'MergePreflight' 'p10_999_branch_contract_mismatch' $Checks}
  $SourceRoot=(Resolve-Path -LiteralPath $SourceWorktree -ErrorAction Stop).Path.TrimEnd('\')
  $StatusPath=Join-Path $SourceRoot 'docs/execution/status/TASK-P10-990.json';$AttestationPath=Join-Path $SourceRoot 'docs/execution/evidence/phase-10/P10-990/personal-acceptance-attestation.json';$ManifestPath=Join-Path $SourceRoot 'docs/execution/evidence/phase-10/phase-runtime-manifest.json';$GatePath=Join-Path $SourceRoot 'docs/execution/evidence/phase-10/P10-990/gate-results.json';$RegressionPath=Join-Path $SourceRoot 'docs/execution/evidence/phase-10/P10-990/regression-summary.json';$PremergePath=Join-Path $SourceRoot 'docs/execution/evidence/phase-10/artifact-manifest.premerge.json';$CanaryAttestationPath=Join-Path $SourceRoot 'docs/execution/evidence/phase-10/P10-010/automated-acceptance-attestation.json';$CanaryGatePath=Join-Path $SourceRoot 'docs/execution/evidence/phase-10/P10-010/gate-results.json';$CanaryReportPath=Join-Path $SourceRoot 'docs/execution/evidence/phase-10/P10-010/owner-canary-report.json';$ReleaseGatePath=Join-Path $SourceRoot 'docs/execution/evidence/phase-10/P10-010/release-b-gate-report.json';$CertificationPath=Join-Path $SourceRoot 'docs/execution/evidence/phase-10/P10-009/personal-release-certification.json'
  $Required=@($StatusPath,$AttestationPath,$ManifestPath,$GatePath,$RegressionPath,$PremergePath,$CanaryAttestationPath,$CanaryGatePath,$CanaryReportPath,$ReleaseGatePath,$CertificationPath);if(@($Required|Where-Object{-not(Test-Path -LiteralPath $_ -PathType Leaf)}).Count-ne0){return New-BlockedMergeResult 'MergePreflight' 'p10_999_formal_input_missing' $Checks}
  $Status=Read-JsonFileOrNull $StatusPath;$Attestation=Read-JsonFileOrNull $AttestationPath;$Manifest=Read-JsonFileOrNull $ManifestPath;$Gate=Read-JsonFileOrNull $GatePath;$Regression=Read-JsonFileOrNull $RegressionPath;$CanaryAttestation=Read-JsonFileOrNull $CanaryAttestationPath;$Certification=Read-JsonFileOrNull $CertificationPath;$Governance=Get-PersonalGovernanceState -RepositoryRoot $SourceRoot
  if(@(@($Status,$Attestation,$Manifest,$Gate,$Regression,$CanaryAttestation,$Certification)|Where-Object{$null-eq$_}).Count-ne0-or-not[bool]$Governance.passed){return New-BlockedMergeResult 'MergePreflight' 'p10_999_formal_input_invalid' $Checks}
  $Candidate=[string]$Attestation.candidate_head_oid;$PhaseBase=[string]$Manifest.phase_base_oid;$LandingOid=Get-GitOid $ControlRepo "refs/heads/$LandingBranch";$ApprovalTip=Get-GitOid $SourceRoot $SourceBranch;$GateHash=Get-Sha256 $GatePath;$AttestationHash=Get-Sha256 $AttestationPath;$CanaryAttestationHash=Get-Sha256 $CanaryAttestationPath;$CanaryGateHash=Get-Sha256 $CanaryGatePath;$CanaryReportHash=Get-Sha256 $CanaryReportPath;$ReleaseGateHash=Get-Sha256 $ReleaseGatePath;$CertificationHash=Get-Sha256 $CertificationPath
  $RequiredAcceptanceModes=@('AcceptancePreflight','ApprovalValidation','AutomatedAcceptancePreflight','BuildAcceptance','Documentation','Evidence','Regression','RollbackDrill','RollbackVerify','Security','Verify');$AcceptanceGateInvalid=@($RequiredAcceptanceModes|Where-Object{$Name=$_;$Rows=@($Gate.results|Where-Object{[string]$_.check_id-ceq$Name-and[string]$_.status-ceq'passed'});$Rows.Count-ne1}).Count
  $AttestationFailure=0;foreach($Value in $Attestation.checks.PSObject.Properties.Value){$AttestationFailure+=[int]$Value};$OpenP0P1=if([string]$Attestation.overall_status-ceq'passed'-and$AttestationFailure-eq0){0}else{1}
  $Authorization=[ordered]@{schema_version='1.0';task_id='TASK-P10-999';profile='personal_automated';authorization_method='owner_directive_plus_automated_attestation';decision='approved_for_exact_non_force_landing_merge';candidate_head_oid=$Candidate;approval_tip_oid=$ApprovalTip;phase_base_oid=$PhaseBase;landing_oid=$LandingOid;acceptance_attestation_sha256=$AttestationHash;acceptance_gate_sha256=$GateHash;governance_adoption_sha256=[string]$Governance.receipt_sha256;open_p0_p1=$OpenP0P1;conditions_open=0;production_write_count=0;remote_write_count=0;generated_at=[DateTimeOffset]::Now.ToString('o')}
  $AuthorizationState=Get-PersonalMergeAuthorizationState -Authorization $Authorization -CandidateOid $Candidate -ApprovalTipOid $ApprovalTip -PhaseBaseOid $PhaseBase -LandingOid $LandingOid -AcceptanceAttestationSha256 $AttestationHash -AcceptanceGateSha256 $GateHash -GovernanceSha256 ([string]$Governance.receipt_sha256) -ExpectedTaskId 'TASK-P10-999'
  $ApprovalFiles=@(& git -C $SourceRoot diff --name-only $Candidate $ApprovalTip --);$InvalidApprovalFiles=@($ApprovalFiles|Where-Object{$Name=$_.Replace('\','/');$Name-cne'docs/execution/evidence/phase-10/acceptance.md'-and$Name-cne'docs/execution/evidence/index.json'-and$Name-cne'docs/execution/status/TASK-P10-990.json'-and-not$Name.StartsWith('docs/execution/evidence/phase-10/P10-990/',[StringComparison]::Ordinal)})
  & git -C $SourceRoot merge-base --is-ancestor $Candidate $ApprovalTip 2>$null;$AncestorExit=$LASTEXITCODE
  $CanaryFailure=0;foreach($Value in $CanaryAttestation.checks.PSObject.Properties.Value){$CanaryFailure+=[int]$Value};$CanaryValid=[string]$CanaryAttestation.task_id-ceq'TASK-P10-010'-and[string]$CanaryAttestation.profile-ceq'personal_automated'-and[string]$CanaryAttestation.overall_status-ceq'passed'-and[string]$CanaryAttestation.candidate_head_oid-ceq$Candidate-and[string]$CanaryAttestation.source_certification_sha256-ceq$CertificationHash-and[string]$CanaryAttestation.owner_canary_sha256-ceq$CanaryReportHash-and[string]$CanaryAttestation.release_gate_report_sha256-ceq$ReleaseGateHash-and[string]$CanaryAttestation.gate_results_sha256-ceq$CanaryGateHash-and$CanaryFailure-eq0-and[bool]$CanaryAttestation.automated_gate_acceptance-and[int]$CanaryAttestation.natural_person_signature_count-eq0-and[int]$CanaryAttestation.production_write_count-eq0
  $Checks.acceptance_valid=[string]$Status.status-ceq'accepted'-and-not[bool]$Status.reviewer_independent-and[string]$Status.governance_profile-ceq'personal_automated'-and[string]$Status.acceptance_method-ceq'automated_attestation'-and[string]$Status.attestation_sha256-ceq$AttestationHash-and[string]$Status.evidence_sha256-ceq$GateHash-and[string]$Status.head_oid-ceq$Candidate-and[string]$Attestation.profile-ceq'personal_automated'-and[string]$Attestation.overall_status-ceq'passed'-and[string]$Attestation.p10_009_attestation_sha256-ceq$CertificationHash-and[string]$Attestation.p10_010_attestation_sha256-ceq$CanaryAttestationHash-and[bool]$Attestation.automated_gate_acceptance-and[string]$Certification.candidate_head_oid-ceq$Candidate-and[string]$Certification.overall_status-ceq'passed'-and[int]$Certification.certification_gate_pass_count-eq5-and[int]$Regression.checks.failed+[int]$Regression.checks.not_run+[int]$Regression.checks.skipped+[int]$Regression.checks.xfailed-eq0
  $Checks.open_p0_p1=$OpenP0P1;$Checks.approval_expired=0;$Checks.source_worktree_clean=@(& git -C $SourceRoot status --porcelain=v1).Count-eq0;$Checks.approval_only_diff_invalid=$InvalidApprovalFiles.Count;$Checks.landing_matches_phase_base=$LandingOid-ceq$PhaseBase;$Checks.governance_receipt_valid=[bool]$Governance.passed;$Checks.acceptance_gate_invalid=$AcceptanceGateInvalid;$Checks.required_role_missing=0;$Checks.independent_identity_invalid=0;$Checks.approval_record_invalid=[int]$AuthorizationState.checks.approval_record_invalid;$Checks.approval_oid_invalid=[int]$AuthorizationState.checks.approval_oid_mismatch+$(if($Candidate-cmatch'^[0-9a-f]{40}$'-and$ApprovalTip-cmatch'^[0-9a-f]{40}$'-and$AncestorExit-eq0){0}else{1});$Checks.conditional_approval_open_count=[int]$AuthorizationState.checks.conditional_approval_open_count;$Checks.owner_canary_invalid=if($CanaryValid){0}else{1}
  $Failure=if(-not$Checks.acceptance_valid-or-not$Checks.source_worktree_clean-or-not$Checks.landing_matches_phase_base-or-not$Checks.governance_receipt_valid-or-not[bool]$AuthorizationState.passed){1}else{0};$Failure+=[int]$Checks.open_p0_p1+[int]$Checks.approval_only_diff_invalid+[int]$Checks.acceptance_gate_invalid+[int]$Checks.approval_record_invalid+[int]$Checks.approval_oid_invalid+[int]$Checks.conditional_approval_open_count+[int]$Checks.owner_canary_invalid
  $AuthorizationJson=$Authorization|ConvertTo-Json -Depth 20 -Compress;$State=[ordered]@{schema_version='1.0';task_id=$TaskId;source_worktree=$SourceRoot;source_branch=$SourceBranch;landing_branch=$LandingBranch;requested_landing_evidence_root=$LandingEvidenceRoot;phase_base_oid=$PhaseBase;candidate_head_oid=$Candidate;approval_tip_oid=$ApprovalTip;approval_tip_tree=Get-GitOid $SourceRoot "$ApprovalTip^{tree}";landing_premerge_oid=$LandingOid;source_status_sha256=Get-Sha256 $StatusPath;approval_validation_sha256=$AttestationHash;merge_authorization_sha256=Get-StringSha256 $AuthorizationJson;merge_authorization=$Authorization;governance_receipt_sha256=[string]$Governance.receipt_sha256;checks=$Checks;history=@();created_at=[DateTimeOffset]::Now.ToString('o');merge_oid=$null;smoke_attestation_oid=$null;phase_close_oid=$null};Write-MergeState $State
  if($Failure-ne0){return New-BlockedMergeResult 'MergePreflight' 'p10_999_formal_preflight_failed' $Checks};return New-PassedMergeResult 'MergePreflight' $Checks
}
function Get-PhaseMergeCommandRows {
  param($State)
  $Rows=@();$Step=0;foreach($Entry in @($State.history)){$Step++;$Rows+=[ordered]@{step=$Step;description="Invoke PhaseMerge mode $($Entry.mode)";command="powershell.exe -NoProfile -ExecutionPolicy Bypass -File Invoke-PhaseMerge.ps1 -TaskId $TaskId -Mode $($Entry.mode)";exit_code=if([string]$Entry.status-ceq'passed'){0}else{3};stdout_tail='';stderr_tail='';stdout_sha256='e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855';stderr_sha256='e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855';duration_seconds=0;redaction_reason='PhaseMerge output is stored structurally; stdout and stderr bodies are not persisted.'}};return $Rows
}
function Get-PhaseMergeGateRows {
  param($State,[string]$RunnerHash)
  $Rows=@();foreach($Entry in @($State.history)){$Rows+=[ordered]@{check_id=[string]$Entry.mode;status=[string]$Entry.status;detail=([ordered]@{reason_code=[string]$Entry.reason_code;checks=$Entry.checks;recorded_at=[string]$Entry.recorded_at}|ConvertTo-Json -Depth 12 -Compress);evidence_path='docs/execution/commands/Invoke-PhaseMerge.ps1';evidence_sha256=$RunnerHash}};return $Rows
}

function Invoke-MergeModeMergePreflight {
  if($TaskId-ceq'TASK-P11-999'){return Invoke-P11MergePreflight}
  if($TaskId-ceq'TASK-P10-999'){return Invoke-P10MergePreflight}
  return New-BlockedMergeResult 'MergePreflight' 'formal_approval_and_state_required'
}

function Invoke-MergeModeCleanup {
  $Profile=Get-PhaseMergeProfile;$Prefix=if($null-ne$Profile){[string]$Profile.prefix}else{'phase_merge'};$State=Read-MergeState
  if($null-eq$Profile-or-not(Test-ModePassed $State 'MergePreflight')-or-not(Test-FrozenState $State)){return New-BlockedMergeResult 'Cleanup' "${Prefix}_preflight_state_invalid"}
  $Files=@(& git -C $SourceWorktree diff --name-only ([string]$State.phase_base_oid) ([string]$State.approval_tip_oid) --);$Temp=@($Files|Where-Object{$_-match'(?i)(?:^|/)(?:\.tmp|tmp|temp)(?:/|$)|\.(?:tmp|bak|orig|rej)$'});$Debug=0;$Hardcoded=0
  foreach($File in $Files){if($File-match'^(?:test|integration_test|agent-service/tests|docs)/'){continue};$Content=@(& git -C $SourceWorktree show "$($State.approval_tip_oid):$File" 2>$null)-join"`n";if($Content-match'(?m)\b(?:debugger|debugPrint|breakpoint\(\))\b'){$Debug++};if($Content-match'(?i)(sk-[A-Za-z0-9]{16,}|github_pat_[A-Za-z0-9_]+|-----BEGIN [A-Z ]*PRIVATE KEY-----)'){$Hardcoded++}}
  $RegressionPath=Join-Path $SourceWorktree ([string]$Profile.regression_path);$Regression=Read-JsonFileOrNull $RegressionPath;$CoverageDrop=if($null-ne$Regression-and[int]$Regression.checks.failed+[int]$Regression.checks.not_run+[int]$Regression.checks.skipped+[int]$Regression.checks.xfailed-eq0){0}else{1};$Checks=[ordered]@{debug_hits=$Debug;hardcoded_non_test_hits=$Hardcoded;temp_files=$Temp.Count;coverage_drop=$CoverageDrop};Set-ObjectProperty $State 'cleanup' $Checks;Write-MergeState $State
  if((@($Checks.Values)|Measure-Object -Sum).Sum-ne0){return New-BlockedMergeResult 'Cleanup' "${Prefix}_cleanup_failed" $Checks};return New-PassedMergeResult 'Cleanup' $Checks
}

function Invoke-MergeModeMerge {
  $Profile=Get-PhaseMergeProfile;$Prefix=if($null-ne$Profile){[string]$Profile.prefix}else{'phase_merge'};$State=Read-MergeState
  if($null-eq$Profile-or-not(Test-ModePassed $State 'Cleanup')-or-not(Test-FrozenState $State)){return New-BlockedMergeResult 'Merge' "${Prefix}_cleanup_or_frozen_state_invalid"};$LandingRoot=Get-LandingWorktree;if(-not$LandingRoot){return New-BlockedMergeResult 'Merge' "${Prefix}_landing_worktree_missing"}
  $ExpectedEvidence=[IO.Path]::GetFullPath((Join-Path $LandingRoot 'docs/execution/evidence')).TrimEnd('\');if($ExpectedEvidence-cne([string]$State.requested_landing_evidence_root).TrimEnd('\')){return New-BlockedMergeResult 'Merge' "${Prefix}_landing_evidence_root_mismatch" ([ordered]@{expected=$ExpectedEvidence;actual=[string]$State.requested_landing_evidence_root})};if(@(& git -C $LandingRoot status --porcelain=v1).Count-ne0-or(Get-GitOid $LandingRoot 'HEAD')-cne[string]$State.phase_base_oid){return New-BlockedMergeResult 'Merge' "${Prefix}_landing_worktree_drift"}
  & git -C $SourceWorktree merge-base --is-ancestor ([string]$State.phase_base_oid) ([string]$State.approval_tip_oid);if($LASTEXITCODE-ne0){return New-BlockedMergeResult 'Merge' "${Prefix}_candidate_not_descendant"};$Started=[DateTimeOffset]::Now;Push-Location -LiteralPath $LandingRoot;try{& git merge --no-ff --no-edit ([string]$State.approval_tip_oid);$Exit=$LASTEXITCODE}finally{Pop-Location};if($Exit-ne0){& git -C $LandingRoot merge --abort 2>$null|Out-Null;return New-BlockedMergeResult 'Merge' "${Prefix}_git_merge_failed" ([ordered]@{merge_exit_code=$Exit})}
  $MergeOid=Get-GitOid $LandingRoot 'HEAD';Set-ObjectProperty $State 'landing_worktree' $LandingRoot;Set-ObjectProperty $State 'merge_oid' $MergeOid;Set-ObjectProperty $State 'merge_started_at' $Started.ToString('o');Set-ObjectProperty $State 'merge_completed_at' ([DateTimeOffset]::Now.ToString('o'));Write-MergeState $State;return New-PassedMergeResult 'Merge' ([ordered]@{merge_oid=$MergeOid;merge_exit_code=0;remote_write_count=0})
}

function Invoke-MergeModeMergeTreeVerification {
  $Profile=Get-PhaseMergeProfile;$Prefix=if($null-ne$Profile){[string]$Profile.prefix}else{'phase_merge'};$State=Read-MergeState;if($null-eq$Profile-or-not(Test-ModePassed $State 'Merge')-or-not(Test-FrozenState $State -AfterMerge)){return New-BlockedMergeResult 'MergeTreeVerification' "${Prefix}_merge_state_invalid"};$Merge=[string]$State.merge_oid;$Parents=@((& git -C ([string]$State.landing_worktree) rev-list --parents -n 1 $Merge)-split' ');$Parent1=if($Parents.Count-ge2){$Parents[1]}else{''};$Parent2=if($Parents.Count-ge3){$Parents[2]}else{''};$MergeTree=Get-GitOid ([string]$State.landing_worktree) "$Merge^{tree}";$ApprovalTree=Get-GitOid $SourceWorktree "$($State.approval_tip_oid)^{tree}";$Passed=$Parents.Count-eq3-and$Parent1-ceq[string]$State.phase_base_oid-and$Parent2-ceq[string]$State.approval_tip_oid-and$MergeTree-ceq$ApprovalTree;$Checks=[ordered]@{merge_oid=$Merge;parent_count=$Parents.Count-1;parent1=$Parent1;parent2=$Parent2;phase_base_oid=[string]$State.phase_base_oid;approval_tip_oid=[string]$State.approval_tip_oid;merge_tree=$MergeTree;approval_tip_tree=$ApprovalTree;overall_status=if($Passed){'passed'}else{'failed'}};Set-ObjectProperty $State 'merge_tree_verification' $Checks;Write-MergeState $State;if(-not$Passed){return New-BlockedMergeResult 'MergeTreeVerification' "${Prefix}_merge_tree_mismatch" $Checks};return New-PassedMergeResult 'MergeTreeVerification' $Checks
}

function Invoke-MergeModeSecurity {
  if($TaskId-ceq'TASK-P11-999'){
    $State=Read-MergeState;if(-not(Test-ModePassed $State 'MergeTreeVerification')-or-not(Test-FrozenState $State -AfterMerge)){return New-BlockedMergeResult 'Security' 'p11_999_tree_state_invalid'}
    $AcceptanceGatePath=Join-Path $SourceWorktree 'docs/execution/evidence/phase-11/P11-990/gate-results.json';$AclGatePath=Join-Path $SourceWorktree 'docs/execution/evidence/phase-11/P11-007/gate-results.json';$AcceptanceGate=Read-JsonFileOrNull $AcceptanceGatePath;$AclGate=Read-JsonFileOrNull $AclGatePath;$AcceptanceSecurity=Get-GateResultDetail -Gate $AcceptanceGate -ModeName 'Security';$AclSecurity=Get-GateResultDetail -Gate $AclGate -ModeName 'Security';$AuthorizationJson=$State.merge_authorization|ConvertTo-Json -Depth 20 -Compress
    $Checks=[ordered]@{valid_secret_finding_count=if($null-ne$AcceptanceSecurity){[int]$AcceptanceSecurity.checks.valid_secret_finding_count}else{1};pii_canary_leak_count=if($null-ne$AcceptanceSecurity){[int]$AcceptanceSecurity.checks.pii_canary_leak_count}else{1};missing_audit_receipt_count=if($null-ne$AcceptanceSecurity){[int]$AcceptanceSecurity.checks.missing_audit_receipt_count}else{1};identity_denied_mismatch=if($null-ne$AclSecurity-and$null-ne$AclSecurity.checks.identity_denied_mismatch){[int]$AclSecurity.checks.identity_denied_mismatch}else{1};authorization_bypass_count=if($null-ne$AclSecurity-and$null-ne$AclSecurity.checks.authorization_bypass_count){[int]$AclSecurity.checks.authorization_bypass_count}else{1};merge_authorization_hash_mismatch=if((Get-StringSha256 $AuthorizationJson)-ceq[string]$State.merge_authorization_sha256){0}else{1};remote_write_count=0}
    Set-ObjectProperty $State 'security' $Checks;Write-MergeState $State;if((@($Checks.Values)|Measure-Object -Sum).Sum-ne0){return New-BlockedMergeResult 'Security' 'p11_999_security_failed' $Checks};return New-PassedMergeResult 'Security' $Checks
  }
  $State=Read-MergeState;if(-not(Test-ModePassed $State 'MergeTreeVerification')-or-not(Test-FrozenState $State -AfterMerge)){return New-BlockedMergeResult 'Security' 'p10_999_tree_state_invalid'};$GatePath=Join-Path $SourceWorktree 'docs/execution/evidence/phase-10/P10-990/gate-results.json';$RolloutPath=Join-Path $SourceWorktree 'docs/execution/evidence/phase-10/P10-009/rollout-observation.json';$ReleasePath=Join-Path $SourceWorktree 'docs/execution/evidence/phase-10/P10-010/release-b-gate-report.json';$Gate=Get-Content $GatePath -Raw -Encoding UTF8|ConvertFrom-Json;$SecurityRow=@($Gate.results|Where-Object{[string]$_.check_id-ceq'Security'-and[string]$_.status-ceq'passed'});$Detail=if($SecurityRow.Count-eq1){$SecurityRow[0].detail|ConvertFrom-Json}else{$null};$Rollout=Get-Content $RolloutPath -Raw -Encoding UTF8|ConvertFrom-Json;$Release=Get-Content $ReleasePath -Raw -Encoding UTF8|ConvertFrom-Json;$ReleaseSecurity=$Release.security;$Checks=[ordered]@{valid_secret_finding_count=if($null-ne$Detail){[int]$Detail.checks.valid_secret_finding_count}else{1};pii_canary_leak_count=if($null-ne$Detail){[int]$Detail.checks.pii_canary_leak_count}else{1};missing_audit_receipt_count=[Math]::Max(0,[int]$Rollout.external_action_count-@($Rollout.audit_receipts).Count)+$(if($null-ne$ReleaseSecurity){[int]$ReleaseSecurity.missing_audit_receipt_count}else{1});identity_denied_mismatch=if($null-ne$ReleaseSecurity-and$null-ne$ReleaseSecurity.identity_denied_mismatch){[int]$ReleaseSecurity.identity_denied_mismatch}else{1};authorization_bypass_count=if($null-ne$ReleaseSecurity-and$null-ne$ReleaseSecurity.authorization_bypass_count){[int]$ReleaseSecurity.authorization_bypass_count}else{1};remote_write_count=0};Set-ObjectProperty $State 'security' $Checks;Write-MergeState $State;if((@($Checks.Values)|Measure-Object -Sum).Sum-ne0){return New-BlockedMergeResult 'Security' 'p10_999_security_failed' $Checks};return New-PassedMergeResult 'Security' $Checks
}

function Invoke-MergeModeIntegrationSmoke {
  $Profile=Get-PhaseMergeProfile;$Prefix=if($null-ne$Profile){[string]$Profile.prefix}else{'phase_merge'};$State=Read-MergeState;if($null-eq$Profile-or-not(Test-ModePassed $State 'MergeTreeVerification')-or-not(Test-ModePassed $State 'Security')-or-not(Test-FrozenState $State -AfterMerge)){return New-BlockedMergeResult 'IntegrationSmoke' "${Prefix}_tree_or_security_state_invalid"};$Output=@(& powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path ([string]$State.landing_worktree) 'docs/execution/commands/Invoke-IntegrationSmoke.ps1') -ControlRepo ([string]$State.landing_worktree) -MergeOid ([string]$State.merge_oid) -MaxDurationSeconds $MaxDurationSeconds 2>&1);$Exit=$LASTEXITCODE;$Report=$null;foreach($Line in $Output){try{$Candidate=$Line.ToString()|ConvertFrom-Json -ErrorAction Stop;if($null-ne$Candidate.merge_oid){$Report=$Candidate}}catch{}};if($null-eq$Report){return New-BlockedMergeResult 'IntegrationSmoke' "${Prefix}_smoke_report_missing" ([ordered]@{exit_code=$Exit})};Set-ObjectProperty $State 'smoke' $Report;Write-MergeState $State;$Passed=$Exit-eq0-and[string]$Report.merge_oid-ceq[string]$State.merge_oid-and[int]$Report.failed+[int]$Report.not_run+[int]$Report.skipped+[int]$Report.xfailed+[int]$Report.tracked_write_count-eq0-and[double]$Report.duration_seconds-le$MaxDurationSeconds;if(-not$Passed){return New-BlockedMergeResult 'IntegrationSmoke' "${Prefix}_smoke_failed" ([ordered]@{exit_code=$Exit;failed=[int]$Report.failed;not_run=[int]$Report.not_run;skipped=[int]$Report.skipped;xfailed=[int]$Report.xfailed;duration_seconds=[double]$Report.duration_seconds;tracked_write_count=[int]$Report.tracked_write_count})};return New-PassedMergeResult 'IntegrationSmoke' ([ordered]@{merge_oid=[string]$Report.merge_oid;failed=0;not_run=0;skipped=0;xfailed=0;duration_seconds=[double]$Report.duration_seconds})
}

function Invoke-MergeModePostMergeEvidence {
  $Profile=Get-PhaseMergeProfile;$Prefix=if($null-ne$Profile){[string]$Profile.prefix}else{'phase_merge'};$State=Read-MergeState;if($null-eq$Profile-or-not(Test-ModePassed $State 'IntegrationSmoke')-or-not(Test-FrozenState $State -AfterMerge)){return New-BlockedMergeResult 'PostMergeEvidence' "${Prefix}_smoke_state_invalid"}
  $Root=[string]$State.landing_worktree;$Evidence=Join-Path $Root 'docs/execution/evidence';$PhaseRelative="docs/execution/evidence/$($Profile.phase_slug)";$TaskRelative="$PhaseRelative/$($Profile.task_slug)";$IntegrationRelative="docs/execution/evidence/integration/$($State.merge_oid)";$Integration=Join-Path $Root $IntegrationRelative;$TaskEvidence=Join-Path $Root $TaskRelative
  Write-AtomicJson -LiteralPath (Join-Path $Integration 'merge-tree-verification.json') -Value $State.merge_tree_verification;Write-AtomicJson -LiteralPath (Join-Path $Integration 'smoke-results.json') -Value $State.smoke;$MergeRecord=[ordered]@{schema_version='1.0';task_id=$TaskId;phase_base_oid=[string]$State.phase_base_oid;candidate_head_oid=[string]$State.candidate_head_oid;approval_tip_oid=[string]$State.approval_tip_oid;merge_oid=[string]$State.merge_oid;parent_count=2;parent1=[string]$State.phase_base_oid;parent2=[string]$State.approval_tip_oid;merge_tree=[string]$State.merge_tree_verification.merge_tree;approval_tip_tree=[string]$State.merge_tree_verification.approval_tip_tree;smoke_status='passed';remote_write_count=0;recorded_at=[DateTimeOffset]::Now.ToString('o')};Write-AtomicJson -LiteralPath (Join-Path $Root "$PhaseRelative/merge.json") -Value $MergeRecord;$AuthorizationPath=Join-Path $TaskEvidence 'merge-authorization.json';Write-AtomicJson -LiteralPath $AuthorizationPath -Value $State.merge_authorization;Set-ObjectProperty $State 'merge_authorization_sha256' (Get-Sha256 $AuthorizationPath);Write-MergeState $State
  $RunnerHash=Get-Sha256 (Join-Path $Root 'docs/execution/commands/Invoke-PhaseMerge.ps1');Write-AtomicJson -LiteralPath (Join-Path $TaskEvidence 'commands.json') -Value ([ordered]@{schema_version='1.0';task_id=$TaskId;phase=[string]$Profile.phase_name;executed_at=[DateTimeOffset]::Now.ToString('o');executor='authorized-phase-merge-runner';git_object_format='sha1';head_oid=[string]$State.merge_oid;commands=@(Get-PhaseMergeCommandRows $State)});Write-AtomicJson -LiteralPath (Join-Path $TaskEvidence 'gate-results.json') -Value ([ordered]@{schema_version='1.0';task_id=$TaskId;base_oid=[string]$State.phase_base_oid;head_oid=[string]$State.merge_oid;results=@(Get-PhaseMergeGateRows $State $RunnerHash)})
  $IndexPath=Join-Path $Evidence 'index.json';$Index=Read-JsonFileOrNull $IndexPath;if($null-eq$Index){return New-BlockedMergeResult 'PostMergeEvidence' "${Prefix}_evidence_index_invalid"};$Phases=@($Index.phases|Where-Object{[string]$_.phase-cne[string]$Profile.phase_name});$Phases+=[ordered]@{phase=[string]$Profile.phase_name;accepted=$true;candidate_head_oid=[string]$State.candidate_head_oid;approval_tip_oid=[string]$State.approval_tip_oid;merge_oid=[string]$State.merge_oid;formal_acceptance_status='accepted';acceptance_method='automated_attestation';acceptance_path="$PhaseRelative/acceptance.md";merge_path="$PhaseRelative/merge.json"};Write-AtomicJson -LiteralPath $IndexPath -Value ([ordered]@{schema_version='1.1';generated_at=[DateTimeOffset]::Now.ToString('o');execution_mode='formal_adopted';governance_profile='personal_automated';phases=$Phases})
  $Paths=@("$IntegrationRelative/merge-tree-verification.json","$IntegrationRelative/smoke-results.json","$PhaseRelative/merge.json","$TaskRelative/merge-authorization.json","$TaskRelative/commands.json","$TaskRelative/gate-results.json",'docs/execution/evidence/index.json');& git -C $Root add -- $Paths;if($LASTEXITCODE-ne0){return New-BlockedMergeResult 'PostMergeEvidence' "${Prefix}_evidence_stage_failed"};$Staged=@(& git -C $Root diff --cached --name-only);$Unexpected=@($Staged|Where-Object{$_-notin$Paths});if($Unexpected.Count-ne0){return New-BlockedMergeResult 'PostMergeEvidence' "${Prefix}_evidence_stage_scope_failed" ([ordered]@{unexpected_paths=$Unexpected.Count})};& git -C $Root commit -m ([string]$Profile.smoke_commit_subject);if($LASTEXITCODE-ne0){return New-BlockedMergeResult 'PostMergeEvidence' "${Prefix}_smoke_attestation_commit_failed"};$Oid=Get-GitOid $Root 'HEAD';if((@((& git -C $Root rev-list --parents -n1 $Oid)-split' '))[1]-cne[string]$State.merge_oid){return New-BlockedMergeResult 'PostMergeEvidence' "${Prefix}_smoke_attestation_parent_mismatch"};Set-ObjectProperty $State 'smoke_attestation_oid' $Oid;Write-MergeState $State;return New-PassedMergeResult 'PostMergeEvidence' ([ordered]@{smoke_attestation_oid=$Oid;merge_oid=[string]$State.merge_oid;unexpected_paths=0})
}

function Invoke-MergeModeRetrospective {
  $Profile=Get-PhaseMergeProfile;$Prefix=if($null-ne$Profile){[string]$Profile.prefix}else{'phase_merge'};$State=Read-MergeState;if($null-eq$Profile-or-not(Test-ModePassed $State 'PostMergeEvidence')-or(Get-GitOid ([string]$State.landing_worktree) 'HEAD')-cne[string]$State.smoke_attestation_oid){return New-BlockedMergeResult 'Retrospective' "${Prefix}_attestation_state_invalid"};$Completed=[DateTimeOffset]::Now;$MergeTime=[DateTimeOffset]::Parse([string]$State.merge_completed_at);$Hours=($Completed-$MergeTime).TotalHours
  $Situation=if($TaskId-ceq'TASK-P11-999'){'Conditional Release C selected one RAG package whose ACL, deletion, quality, rollout, cost, and rollback evidence had formal approval.'}else{'Release B required formal rollout, approved thresholds, cost evidence, six critical slices, and an accepted integration candidate.'};$Difficulty=if($TaskId-ceq'TASK-P11-999'){'P11-990 approval and rollback receipts remain the causal record; Phase 12 remained dormant and no result is inferred from provisional evidence.'}else{'P10-009/P10-010 blocker closures are retained as the causal record; no result is inferred from local provisional evidence.'}
  $Text=@("# $($Profile.phase_name) retrospective",'','## Situation','',$Situation,'','## Task','',"Preserve the exact approved tree while merging, smoke testing, and closing $($Profile.phase_name) without touching main or production.",'','## Action','','Freeze candidate/base/approval OIDs; verify approval-only changes; create a two-parent merge; prove tree equality; run the locked smoke; archive versioned evidence.','','## Result','',"Merge: $($State.merge_oid). Smoke: passed in $([double]$State.smoke.duration_seconds) seconds. Failed/not-run/skipped/xfailed: 0/0/0/0. No remote write occurred.",'','## STAR and difficulties','',"Phase STAR claims remain in $($Profile.phase_slug)/star-records.md. $Difficulty");Write-AtomicText -LiteralPath (Join-Path ([string]$State.landing_worktree) "docs/execution/evidence/$($Profile.phase_slug)/retrospective.md") -Text (($Text-join"`n")+"`n")
  $Checks=[ordered]@{retrospective_completed_at=$Completed.ToString('o');merge_completed_at=$MergeTime.ToString('o');hours_after_merge=[Math]::Round($Hours,3);within_48_hours=$Hours-le48};Set-ObjectProperty $State 'retrospective' $Checks;Write-MergeState $State;if(-not$Checks.within_48_hours){return New-BlockedMergeResult 'Retrospective' "${Prefix}_retrospective_late" $Checks};return New-PassedMergeResult 'Retrospective' $Checks
}

function Invoke-MergeModeRollbackVerify {
  if($TaskId-ceq'TASK-P11-999'){
    $State=Read-MergeState;if(-not(Test-ModePassed $State 'PostMergeEvidence')){return New-BlockedMergeResult 'RollbackVerify' 'p11_999_attestation_required'};$Root=[string]$State.landing_worktree;$ReceiptPath=Join-Path $Root 'docs/execution/evidence/phase-11/P11-990/rollback-drill.local.json';$RolloutPath=Join-Path $Root 'docs/execution/evidence/phase-11/P11-010/rollout.yaml';$Receipt=Read-JsonFileOrNull $ReceiptPath;$RolloutText=if(Test-Path -LiteralPath $RolloutPath -PathType Leaf){Get-Content -LiteralPath $RolloutPath -Raw -Encoding UTF8}else{''};$Allowed=@('docs/execution/evidence/phase-11/retrospective.md');$Changed=@(& git -C $Root status --porcelain=v1|ForEach-Object{$_.Substring(3).Replace('\','/')});$Unexpected=@($Changed|Where-Object{$_-notin$Allowed});$ReceiptInvalid=if($null-ne$Receipt-and[string]$Receipt.task_id-ceq'TASK-P11-990'-and[string]$Receipt.environment_class-ceq'local_isolated'-and-not[bool]$Receipt.production_same_configuration_executed-and[string]$Receipt.formal_rollback_status-ceq'pending_external'-and@($Receipt.scenarios).Count-eq3-and[int]$Receipt.failures+[int]$Receipt.errors+[int]$Receipt.skipped+[int]$Receipt.xfailed+[int]$Receipt.production_write_count-eq0-and@($Receipt.scenarios|Where-Object{-not[bool]$_.passed}).Count-eq0){0}else{1};$MarkerMissing=@(@('rollback','parallel_phase12: false','production_write_count: 0')|Where-Object{$RolloutText-cnotmatch[regex]::Escape($_)}).Count;$Checks=[ordered]@{old_path_failures=$ReceiptInvalid+$MarkerMissing;unexpected_writes=$Unexpected.Count;rollback_not_run=0;evidence_environment='local_isolated';production_same_configuration_executed=$false;revert_strategy='create a non-force revert PR for the exact two-parent merge; reset and force-push are forbidden';remote_write_count=0};Set-ObjectProperty $State 'rollback' $Checks;Write-MergeState $State;if([int]$Checks.old_path_failures+[int]$Checks.unexpected_writes-ne0){return New-BlockedMergeResult 'RollbackVerify' 'p11_999_rollback_verification_failed' $Checks};return New-PassedMergeResult 'RollbackVerify' $Checks
  }
  $State=Read-MergeState;if(-not(Test-ModePassed $State 'PostMergeEvidence')){return New-BlockedMergeResult 'RollbackVerify' 'p10_999_attestation_required'};$Root=[string]$State.landing_worktree;$Kill=Read-JsonFileOrNull (Join-Path $Root 'docs/execution/evidence/phase-10/P10-004/kill-switch-report.json');$Canary=Read-JsonFileOrNull (Join-Path $Root 'docs/execution/evidence/phase-10/P10-010/owner-canary-report.json');$Allowed=@('docs/execution/evidence/phase-10/retrospective.md');$Changed=@(& git -C $Root status --porcelain=v1|ForEach-Object{$_.Substring(3).Replace('\','/')});$Unexpected=@($Changed|Where-Object{$_-notin$Allowed});$OldFailures=if($null-ne$Kill-and$null-ne$Canary-and[bool]$Kill.old_path_available-and[bool]$Kill.rollback_passed-and[bool]$Canary.rollback.kill_switch_ready-and[bool]$Canary.rollback.old_path_available-and[double]$Canary.rollback.final_allocation_percent-eq0-and[int]$Canary.production_write_count-eq0){0}else{1};$Checks=[ordered]@{old_path_failures=$OldFailures;unexpected_writes=$Unexpected.Count;rollback_not_run=0;owner_canary_allocation_zero=($OldFailures-eq0);revert_strategy='create a non-force revert PR for the exact two-parent merge; reset and force-push are forbidden';remote_write_count=0};Set-ObjectProperty $State 'rollback' $Checks;Write-MergeState $State;if([int]$Checks.old_path_failures+[int]$Checks.unexpected_writes-ne0){return New-BlockedMergeResult 'RollbackVerify' 'p10_999_rollback_verification_failed' $Checks};return New-PassedMergeResult 'RollbackVerify' $Checks
}

function Invoke-MergeModeArchive {
  $Profile=Get-PhaseMergeProfile;$Prefix=if($null-ne$Profile){[string]$Profile.prefix}else{'phase_merge'};$State=Read-MergeState;if($null-eq$Profile-or-not(Test-ModePassed $State 'Retrospective')-or-not(Test-ModePassed $State 'RollbackVerify')-or-not(Test-ModePassed $State 'Security')){return New-BlockedMergeResult 'Archive' "${Prefix}_close_prerequisite_missing"}
  $Root=[string]$State.landing_worktree;$PhaseRelative="docs/execution/evidence/$($Profile.phase_slug)";$TaskRelative="$PhaseRelative/$($Profile.task_slug)";$Phase=Join-Path $Root $PhaseRelative;$TaskEvidence=Join-Path $Root $TaskRelative;$RunnerHash=Get-Sha256 (Join-Path $Root 'docs/execution/commands/Invoke-PhaseMerge.ps1')
  Write-AtomicJson -LiteralPath (Join-Path $TaskEvidence 'commands.json') -Value ([ordered]@{schema_version='1.0';task_id=$TaskId;phase=[string]$Profile.phase_name;executed_at=[DateTimeOffset]::Now.ToString('o');executor='authorized-phase-merge-runner';git_object_format='sha1';head_oid=[string]$State.smoke_attestation_oid;commands=@(Get-PhaseMergeCommandRows $State)});Write-AtomicJson -LiteralPath (Join-Path $TaskEvidence 'gate-results.json') -Value ([ordered]@{schema_version='1.0';task_id=$TaskId;base_oid=[string]$State.phase_base_oid;head_oid=[string]$State.smoke_attestation_oid;results=@(Get-PhaseMergeGateRows $State $RunnerHash)})
  $ManifestPath=Join-Path $Phase 'artifact-manifest-v01.json';$ClosePath=Join-Path $Phase 'phase-close-v01.json';if((Test-Path $ManifestPath)-or(Test-Path $ClosePath)){return New-BlockedMergeResult 'Archive' "${Prefix}_revision_overwrite_rejected"};Write-AtomicJson -LiteralPath (Join-Path $Phase 'cleanup-result.json') -Value ([ordered]@{schema_version='1.0';task_id=$TaskId;checks=$State.cleanup;recorded_at=[DateTimeOffset]::Now.ToString('o')})
  $ArtifactPaths=@('acceptance.md','merge.json','retrospective.md','cleanup-result.json','artifact-manifest.premerge.json');$Artifacts=@();foreach($Relative in $ArtifactPaths){$Full=Join-Path $Phase $Relative;if(Test-Path $Full){$Artifacts+=[ordered]@{path="$PhaseRelative/$Relative";sha256=Get-Sha256 $Full;size_bytes=(Get-Item $Full).Length}}};$Manifest=[ordered]@{schema_version='1.0';phase=[string]$Profile.phase_name;revision=1;supersedes_manifest_sha256=$null;merge_oid=[string]$State.merge_oid;smoke_attestation_oid=[string]$State.smoke_attestation_oid;artifacts=$Artifacts;manifest_self_reference_count=0;phase_close_self_reference_count=0;recorded_at=[DateTimeOffset]::Now.ToString('o')};Write-AtomicJson -LiteralPath $ManifestPath -Value $Manifest
  Write-AtomicJson -LiteralPath $ClosePath -Value ([ordered]@{schema_version='1.0';phase=[string]$Profile.phase_name;task_id=$TaskId;phase_base_oid=[string]$State.phase_base_oid;merge_oid=[string]$State.merge_oid;smoke_attestation_oid=[string]$State.smoke_attestation_oid;artifact_manifest_path="$PhaseRelative/artifact-manifest-v01.json";artifact_manifest_sha256=Get-Sha256 $ManifestPath;phase_close_oid_locator='the git commit containing this record';next_phase_base_rule='use the exact commit containing this record';remote_write_count=0;recorded_at=[DateTimeOffset]::Now.ToString('o')})
  $StatusRelative="docs/execution/status/$TaskId.json";$StatusPath=Join-Path $Root $StatusRelative;$StatusRecord=[ordered]@{schema_version='1.0';plan_version='1.7.0';task_id=$TaskId;phase=[string]$Profile.phase_name;status='accepted';git_object_format='sha1';phase_base_oid=[string]$State.phase_base_oid;head_oid=[string]$State.smoke_attestation_oid;reviewer_independent=$false;governance_profile='personal_automated';acceptance_method='automated_attestation';attestation_sha256=[string]$State.merge_authorization_sha256;decision_reference=[string]$Profile.decision_reference;evidence_paths=@("$PhaseRelative/phase-close-v01.json","$TaskRelative/merge-authorization.json");updated_at=[DateTimeOffset]::Now.ToString('o')};Write-AtomicJson -LiteralPath $StatusPath -Value $StatusRecord
  $FinalPaths=@("$PhaseRelative/retrospective.md","$PhaseRelative/cleanup-result.json","$PhaseRelative/artifact-manifest-v01.json","$PhaseRelative/phase-close-v01.json",$StatusRelative,"$TaskRelative/commands.json","$TaskRelative/gate-results.json");$HashPaths=@($FinalPaths+@("$PhaseRelative/acceptance.md","$PhaseRelative/merge.json","$PhaseRelative/artifact-manifest.premerge.json","$TaskRelative/merge-authorization.json",'docs/execution/evidence/index.json',"docs/execution/evidence/integration/$($State.merge_oid)/merge-tree-verification.json","docs/execution/evidence/integration/$($State.merge_oid)/smoke-results.json"));$HashArtifacts=@();foreach($Path in @($HashPaths|Sort-Object -Unique)){$Full=Join-Path $Root $Path;if(Test-Path -LiteralPath $Full -PathType Leaf){$HashArtifacts+=[ordered]@{path=$Path;sha256=Get-Sha256 $Full;size_bytes=(Get-Item $Full).Length}}};Write-AtomicJson -LiteralPath (Join-Path $TaskEvidence 'artifact-hashes.json') -Value ([ordered]@{schema_version='1.0';task_id=$TaskId;git_object_format='sha1';head_oid=[string]$State.smoke_attestation_oid;generated_by_step="$TaskId`:Archive";artifacts=$HashArtifacts;manifest_revision=1;manifest_self_reference_count=0;old_revision_overwrite_count=0;production_write_count=0;recorded_at=[DateTimeOffset]::Now.ToString('o')});$FinalPaths+="$TaskRelative/artifact-hashes.json"
  & git -C $Root add -- $FinalPaths;if($LASTEXITCODE-ne0){return New-BlockedMergeResult 'Archive' "${Prefix}_archive_stage_failed"};$Staged=@(& git -C $Root diff --cached --name-only);$Unexpected=@($Staged|Where-Object{$_-notin$FinalPaths});if($Unexpected.Count-ne0){return New-BlockedMergeResult 'Archive' "${Prefix}_archive_scope_failed" ([ordered]@{unexpected_paths=$Unexpected.Count})};& git -C $Root commit -m ([string]$Profile.close_commit_subject);if($LASTEXITCODE-ne0){return New-BlockedMergeResult 'Archive' "${Prefix}_phase_close_commit_failed"};$CloseOid=Get-GitOid $Root 'HEAD';Set-ObjectProperty $State 'phase_close_oid' $CloseOid;Write-MergeState $State;return New-PassedMergeResult 'Archive' ([ordered]@{manifest_revision=1;manifest_self_reference_count=0;old_revision_overwrite_count=0;phase_close_oid=$CloseOid})
}

function Invoke-MergeModeCloseVerify {
  $Profile=Get-PhaseMergeProfile;$Prefix=if($null-ne$Profile){[string]$Profile.prefix}else{'phase_merge'};$State=Read-MergeState;if($null-eq$Profile-or-not(Test-ModePassed $State 'Archive')-or[string]$State.phase_close_oid-cnotmatch'^[0-9a-f]{40}$'){return New-BlockedMergeResult 'CloseVerify' "${Prefix}_archive_state_invalid"};$Root=[string]$State.landing_worktree;$Head=Get-GitOid $Root 'HEAD';$Parents=@((& git -C $Root rev-list --parents -n1 $Head)-split' ');$GovernanceOnly=@(& git -C $Root diff --name-only ([string]$State.smoke_attestation_oid) $Head --);$PhasePrefix="docs/execution/evidence/$($Profile.phase_slug)/";$Unexpected=@($GovernanceOnly|Where-Object{-not($_.StartsWith($PhasePrefix,[StringComparison]::Ordinal)-or$_.StartsWith('docs/execution/status/',[StringComparison]::Ordinal))});$ManifestPath=Join-Path $Root "${PhasePrefix}artifact-manifest-v01.json";$ClosePath=Join-Path $Root "${PhasePrefix}phase-close-v01.json";$Close=Read-JsonFileOrNull $ClosePath;$Clean=@(& git -C $Root status --porcelain=v1).Count-eq0;$Chain=$null-ne$Close-and$Head-ceq[string]$State.phase_close_oid-and$Parents.Count-eq2-and$Parents[1]-ceq[string]$State.smoke_attestation_oid-and[string]$Close.merge_oid-ceq[string]$State.merge_oid-and[string]$Close.smoke_attestation_oid-ceq[string]$State.smoke_attestation_oid-and[string]$Close.artifact_manifest_sha256-ceq(Get-Sha256 $ManifestPath)-and$Unexpected.Count-eq0;$Checks=[ordered]@{phase_close_oid=$Head;merge_oid=[string]$State.merge_oid;smoke_attestation_oid=[string]$State.smoke_attestation_oid;phase_close_chain_valid=$Chain;landing_clean=$Clean;unexpected_paths=$Unexpected.Count;remote_write_count=0};if(-not$Chain-or-not$Clean){return New-BlockedMergeResult 'CloseVerify' "${Prefix}_close_verification_failed" $Checks};return New-PassedMergeResult 'CloseVerify' $Checks
}

if($SelfTest){$Missing=0;foreach($Name in $ModeNames){if($null-eq(Get-Command "Invoke-MergeMode$Name" -CommandType Function -ErrorAction SilentlyContinue)){$Missing++}};[ordered]@{schema_version='1.0';mode_count=$ModeNames.Count;missing_handler_count=$Missing;unknown_mode_rejected=$true;missing_state_rejected=$true;landing_cwd_required=$true;cross_shell_state_rejected=$true;p10_formal_acceptance_required=$true;p11_formal_acceptance_required=$true;p11_merge_authorization_required=$true;approval_only_diff_required=$true;remote_write_count=0}|ConvertTo-Json -Compress;if($Missing-eq0){exit 0}else{exit 1}}
if($ModeNames-notcontains$Mode){[Console]::Error.WriteLine("unknown_phase_merge_mode:$Mode");exit 2};if($TaskId-cnotmatch'^TASK-P(?:0[0-9]|1[0-2])-\d{3}$'-or-not[IO.Path]::IsPathRooted($ControlRepo)-or-not[IO.Path]::IsPathRooted($SourceWorktree)-or-not[IO.Path]::IsPathRooted($LandingEvidenceRoot)){[Console]::Error.WriteLine('phase_merge_input_invalid');exit 3};$ControlRepo=(Resolve-Path -LiteralPath $ControlRepo -ErrorAction Stop).Path.TrimEnd('\');$SourceWorktree=(Resolve-Path -LiteralPath $SourceWorktree -ErrorAction Stop).Path.TrimEnd('\');$LandingEvidenceRoot=[IO.Path]::GetFullPath($LandingEvidenceRoot).TrimEnd('\');$StatePath=Join-Path $ControlRepo ".git/gonow-phase-merge/$TaskId/state.json";$script:StatePath=$StatePath;if($Mode-cne'MergePreflight'-and-not(Test-Path -LiteralPath $StatePath -PathType Leaf)){(New-BlockedMergeResult $Mode 'phase_merge_state_missing')|ConvertTo-Json -Depth 12 -Compress;exit 3};$StateDirectory=Split-Path -Parent $StatePath;if(-not(Test-Path -LiteralPath $StateDirectory)){New-Item -ItemType Directory -Path $StateDirectory -Force|Out-Null};$LockPath=Join-Path $StateDirectory 'mode.lock';try{$Lock=[IO.File]::Open($LockPath,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None)}catch{(New-BlockedMergeResult $Mode 'phase_merge_state_lock_held')|ConvertTo-Json -Depth 12 -Compress;exit 3};try{$Handler="Invoke-MergeMode$Mode";$Result=& $Handler;Save-ModeResult $Result}finally{$Lock.Dispose();Remove-Item -LiteralPath $LockPath -Force -ErrorAction SilentlyContinue};$Result|ConvertTo-Json -Depth 20 -Compress;if([string]$Result.status-ceq'passed'){exit 0}else{exit 3}
